// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[12];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol\032\037google/protobuf/"
  "timestamp.proto*~\n\nObjectType\022\024\n\020OBJECT_"
  "TYPE_NONE\020\000\022\023\n\017OBJECT_TYPE_ENV\020\001\022\024\n\020OBJE"
  "CT_TYPE_BALL\020\002\022\027\n\023OBJECT_TYPE_ATHLETE\020\003\022"
  "\026\n\022OBJECT_TYPE_PLAYER\020\004*c\n\010RoomType\022\022\n\016R"
  "OOM_TYPE_NONE\020\000\022\023\n\017ROOM_TYPE_LOBBY\020\001\022\025\n\021"
  "ROOM_TYPE_MEETING\020\002\022\027\n\023ROOM_TYPE_TEAMMAT"
  "CH\020\003*\203\001\n\013AthleteRace\022\025\n\021ATHLETE_RACE_NON"
  "E\020\000\022\026\n\022ATHLETE_RACE_HUMAN\020\001\022\026\n\022ATHLETE_R"
  "ACE_SLIME\020\002\022\027\n\023ATHLETE_RACE_GEARON\020\003\022\024\n\020"
  "ATHLETE_RACE_ROO\020\004*\203\001\n\017AthletePosition\022\031"
  "\n\025ATHLETE_POSITION_NONE\020\000\022\034\n\030ATHLETE_POS"
  "ITION_FORWARD\020\001\022\032\n\026ATHLETE_POSITION_GUAR"
  "D\020\002\022\033\n\027ATHLETE_POSITION_CENTER\020\003*\"\n\nAthl"
  "eteTag\022\024\n\020ATHLETE_TAG_NONE\020\000*\304\001\n\014Emotion"
  "State\022\026\n\022EMOTION_STATE_NONE\020\000\022\030\n\024EMOTION"
  "_STATE_NORMAL\020\001\022\033\n\027EMOTION_STATE_CONFIDE"
  "NT\020\002\022\027\n\023EMOTION_STATE_ANGRY\020\003\022\032\n\026EMOTION"
  "_STATE_INSECURE\020\004\022\030\n\024EMOTION_STATE_RUSHE"
  "D\020\005\022\026\n\022EMOTION_STATE_HURT\020\006*j\n\nInjuryTyp"
  "e\022\024\n\020INJURY_TYPE_NONE\020\000\022\026\n\022INJURY_TYPE_S"
  "PRAIN\020\001\022\024\n\020INJURY_TYPE_TEAR\020\002\022\030\n\024INJURY_"
  "TYPE_FRACTURE\020\003*|\n\010Bodypart\022\021\n\rBODYPART_"
  "NONE\020\000\022\022\n\016BODYPART_ANKLE\020\001\022\020\n\014BODYPART_L"
  "EG\020\002\022\021\n\rBODYPART_KNEE\020\003\022\021\n\rBODYPART_BACK"
  "\020\004\022\021\n\rBODYPART_HAND\020\005*\346\001\n\tMoveState\022\023\n\017M"
  "OVE_STATE_NONE\020\000\022\023\n\017MOVE_STATE_IDLE\020\001\022\023\n"
  "\017MOVE_STATE_WALK\020\002\022\026\n\022MOVE_STATE_PHYSICS"
  "\020\003\022\032\n\026MOVE_STATE_FOLLOW_PATH\020\004\022\022\n\016MOVE_S"
  "TATE_RUN\020\005\022\023\n\017MOVE_STATE_JUMP\020\006\022\024\n\020MOVE_"
  "STATE_STEAL\020\007\022\022\n\016MOVE_STATE_HIT\020\010\022\023\n\017MOV"
  "E_STATE_HURT\020\t*\225\001\n\tTeamState\022\023\n\017TEAM_STA"
  "TE_NONE\020\000\022\026\n\022TEAM_STATE_OFFENSE\020\001\022\026\n\022TEA"
  "M_STATE_DEFENSE\020\002\022\031\n\025TEAM_STATE_LOOSE_BA"
  "LL\020\003\022\024\n\020TEAM_STATE_BREAK\020\004\022\022\n\016TEAM_STATE"
  "_END\020\005*$\n\013TacticsType\022\025\n\021TACTICS_TYPE_NO"
  "NE\020\000*\227\001\n\rTeamMatchType\022\030\n\024TEAM_MATCH_TYP"
  "E_NONE\020\000\022\032\n\026TEAM_MATCH_TYPE_SEASON\020\001\022\030\n\024"
  "TEAM_MATCH_TYPE_FREE\020\002\022\033\n\027TEAM_MATCH_TYP"
  "E_PLAYOFF\020\003\022\031\n\025TEAM_MATCH_TYPE_FINAL\020\004B\027"
  "\252\002\024Google.Protobuf.Enumb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Enum_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 1631, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, descriptor_table_Enum_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RoomType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool RoomType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AthleteRace_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool AthleteRace_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AthletePosition_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool AthletePosition_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AthleteTag_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool AthleteTag_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EmotionState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[5];
}
bool EmotionState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* InjuryType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[6];
}
bool InjuryType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Bodypart_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[7];
}
bool Bodypart_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[8];
}
bool MoveState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TeamState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[9];
}
bool TeamState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TacticsType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[10];
}
bool TacticsType_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TeamMatchType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[11];
}
bool TeamMatchType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
