// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HttpProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HttpProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HttpProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HttpProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HttpProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HttpProtocol_2eproto;
namespace Protocol {
class REQ_CHECK_EXISTS_ACCOUNT;
struct REQ_CHECK_EXISTS_ACCOUNTDefaultTypeInternal;
extern REQ_CHECK_EXISTS_ACCOUNTDefaultTypeInternal _REQ_CHECK_EXISTS_ACCOUNT_default_instance_;
class REQ_CONNECT_GAME_SERVER;
struct REQ_CONNECT_GAME_SERVERDefaultTypeInternal;
extern REQ_CONNECT_GAME_SERVERDefaultTypeInternal _REQ_CONNECT_GAME_SERVER_default_instance_;
class REQ_CREATE_ACCOUNT;
struct REQ_CREATE_ACCOUNTDefaultTypeInternal;
extern REQ_CREATE_ACCOUNTDefaultTypeInternal _REQ_CREATE_ACCOUNT_default_instance_;
class REQ_LOGIN_ACCOUNT;
struct REQ_LOGIN_ACCOUNTDefaultTypeInternal;
extern REQ_LOGIN_ACCOUNTDefaultTypeInternal _REQ_LOGIN_ACCOUNT_default_instance_;
class REQ_LOGIN_GOOGLE_ACCOUNT;
struct REQ_LOGIN_GOOGLE_ACCOUNTDefaultTypeInternal;
extern REQ_LOGIN_GOOGLE_ACCOUNTDefaultTypeInternal _REQ_LOGIN_GOOGLE_ACCOUNT_default_instance_;
class REQ_RECHECK_SERVER;
struct REQ_RECHECK_SERVERDefaultTypeInternal;
extern REQ_RECHECK_SERVERDefaultTypeInternal _REQ_RECHECK_SERVER_default_instance_;
class RES_CHECK_EXISTS_ACCOUNT;
struct RES_CHECK_EXISTS_ACCOUNTDefaultTypeInternal;
extern RES_CHECK_EXISTS_ACCOUNTDefaultTypeInternal _RES_CHECK_EXISTS_ACCOUNT_default_instance_;
class RES_CONNECT_GAME_SERVER;
struct RES_CONNECT_GAME_SERVERDefaultTypeInternal;
extern RES_CONNECT_GAME_SERVERDefaultTypeInternal _RES_CONNECT_GAME_SERVER_default_instance_;
class RES_CREATE_ACCOUNT;
struct RES_CREATE_ACCOUNTDefaultTypeInternal;
extern RES_CREATE_ACCOUNTDefaultTypeInternal _RES_CREATE_ACCOUNT_default_instance_;
class RES_LOGIN_ACCOUNT;
struct RES_LOGIN_ACCOUNTDefaultTypeInternal;
extern RES_LOGIN_ACCOUNTDefaultTypeInternal _RES_LOGIN_ACCOUNT_default_instance_;
class RES_RECHECK_SERVER;
struct RES_RECHECK_SERVERDefaultTypeInternal;
extern RES_RECHECK_SERVERDefaultTypeInternal _RES_RECHECK_SERVER_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::REQ_CHECK_EXISTS_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::REQ_CHECK_EXISTS_ACCOUNT>(Arena*);
template<> ::Protocol::REQ_CONNECT_GAME_SERVER* Arena::CreateMaybeMessage<::Protocol::REQ_CONNECT_GAME_SERVER>(Arena*);
template<> ::Protocol::REQ_CREATE_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::REQ_CREATE_ACCOUNT>(Arena*);
template<> ::Protocol::REQ_LOGIN_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::REQ_LOGIN_ACCOUNT>(Arena*);
template<> ::Protocol::REQ_LOGIN_GOOGLE_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::REQ_LOGIN_GOOGLE_ACCOUNT>(Arena*);
template<> ::Protocol::REQ_RECHECK_SERVER* Arena::CreateMaybeMessage<::Protocol::REQ_RECHECK_SERVER>(Arena*);
template<> ::Protocol::RES_CHECK_EXISTS_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::RES_CHECK_EXISTS_ACCOUNT>(Arena*);
template<> ::Protocol::RES_CONNECT_GAME_SERVER* Arena::CreateMaybeMessage<::Protocol::RES_CONNECT_GAME_SERVER>(Arena*);
template<> ::Protocol::RES_CREATE_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::RES_CREATE_ACCOUNT>(Arena*);
template<> ::Protocol::RES_LOGIN_ACCOUNT* Arena::CreateMaybeMessage<::Protocol::RES_LOGIN_ACCOUNT>(Arena*);
template<> ::Protocol::RES_RECHECK_SERVER* Arena::CreateMaybeMessage<::Protocol::RES_RECHECK_SERVER>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class REQ_CHECK_EXISTS_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_CHECK_EXISTS_ACCOUNT) */ {
 public:
  inline REQ_CHECK_EXISTS_ACCOUNT() : REQ_CHECK_EXISTS_ACCOUNT(nullptr) {}
  ~REQ_CHECK_EXISTS_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR REQ_CHECK_EXISTS_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_CHECK_EXISTS_ACCOUNT(const REQ_CHECK_EXISTS_ACCOUNT& from);
  REQ_CHECK_EXISTS_ACCOUNT(REQ_CHECK_EXISTS_ACCOUNT&& from) noexcept
    : REQ_CHECK_EXISTS_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline REQ_CHECK_EXISTS_ACCOUNT& operator=(const REQ_CHECK_EXISTS_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_CHECK_EXISTS_ACCOUNT& operator=(REQ_CHECK_EXISTS_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_CHECK_EXISTS_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_CHECK_EXISTS_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const REQ_CHECK_EXISTS_ACCOUNT*>(
               &_REQ_CHECK_EXISTS_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(REQ_CHECK_EXISTS_ACCOUNT& a, REQ_CHECK_EXISTS_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_CHECK_EXISTS_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_CHECK_EXISTS_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_CHECK_EXISTS_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_CHECK_EXISTS_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_CHECK_EXISTS_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_CHECK_EXISTS_ACCOUNT& from) {
    REQ_CHECK_EXISTS_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_CHECK_EXISTS_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_CHECK_EXISTS_ACCOUNT";
  }
  protected:
  explicit REQ_CHECK_EXISTS_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountNameFieldNumber = 1,
  };
  // string account_name = 1;
  void clear_account_name();
  const std::string& account_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_name();
  PROTOBUF_NODISCARD std::string* release_account_name();
  void set_allocated_account_name(std::string* account_name);
  private:
  const std::string& _internal_account_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_name(const std::string& value);
  std::string* _internal_mutable_account_name();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_CHECK_EXISTS_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class RES_CHECK_EXISTS_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.RES_CHECK_EXISTS_ACCOUNT) */ {
 public:
  inline RES_CHECK_EXISTS_ACCOUNT() : RES_CHECK_EXISTS_ACCOUNT(nullptr) {}
  ~RES_CHECK_EXISTS_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR RES_CHECK_EXISTS_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RES_CHECK_EXISTS_ACCOUNT(const RES_CHECK_EXISTS_ACCOUNT& from);
  RES_CHECK_EXISTS_ACCOUNT(RES_CHECK_EXISTS_ACCOUNT&& from) noexcept
    : RES_CHECK_EXISTS_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline RES_CHECK_EXISTS_ACCOUNT& operator=(const RES_CHECK_EXISTS_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline RES_CHECK_EXISTS_ACCOUNT& operator=(RES_CHECK_EXISTS_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RES_CHECK_EXISTS_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const RES_CHECK_EXISTS_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const RES_CHECK_EXISTS_ACCOUNT*>(
               &_RES_CHECK_EXISTS_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RES_CHECK_EXISTS_ACCOUNT& a, RES_CHECK_EXISTS_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(RES_CHECK_EXISTS_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RES_CHECK_EXISTS_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RES_CHECK_EXISTS_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RES_CHECK_EXISTS_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RES_CHECK_EXISTS_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RES_CHECK_EXISTS_ACCOUNT& from) {
    RES_CHECK_EXISTS_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RES_CHECK_EXISTS_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.RES_CHECK_EXISTS_ACCOUNT";
  }
  protected:
  explicit RES_CHECK_EXISTS_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.RES_CHECK_EXISTS_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class REQ_CREATE_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_CREATE_ACCOUNT) */ {
 public:
  inline REQ_CREATE_ACCOUNT() : REQ_CREATE_ACCOUNT(nullptr) {}
  ~REQ_CREATE_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR REQ_CREATE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_CREATE_ACCOUNT(const REQ_CREATE_ACCOUNT& from);
  REQ_CREATE_ACCOUNT(REQ_CREATE_ACCOUNT&& from) noexcept
    : REQ_CREATE_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline REQ_CREATE_ACCOUNT& operator=(const REQ_CREATE_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_CREATE_ACCOUNT& operator=(REQ_CREATE_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_CREATE_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_CREATE_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const REQ_CREATE_ACCOUNT*>(
               &_REQ_CREATE_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(REQ_CREATE_ACCOUNT& a, REQ_CREATE_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_CREATE_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_CREATE_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_CREATE_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_CREATE_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_CREATE_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_CREATE_ACCOUNT& from) {
    REQ_CREATE_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_CREATE_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_CREATE_ACCOUNT";
  }
  protected:
  explicit REQ_CREATE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountNameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string account_name = 1;
  void clear_account_name();
  const std::string& account_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_name();
  PROTOBUF_NODISCARD std::string* release_account_name();
  void set_allocated_account_name(std::string* account_name);
  private:
  const std::string& _internal_account_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_name(const std::string& value);
  std::string* _internal_mutable_account_name();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_CREATE_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class RES_CREATE_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.RES_CREATE_ACCOUNT) */ {
 public:
  inline RES_CREATE_ACCOUNT() : RES_CREATE_ACCOUNT(nullptr) {}
  ~RES_CREATE_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR RES_CREATE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RES_CREATE_ACCOUNT(const RES_CREATE_ACCOUNT& from);
  RES_CREATE_ACCOUNT(RES_CREATE_ACCOUNT&& from) noexcept
    : RES_CREATE_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline RES_CREATE_ACCOUNT& operator=(const RES_CREATE_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline RES_CREATE_ACCOUNT& operator=(RES_CREATE_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RES_CREATE_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const RES_CREATE_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const RES_CREATE_ACCOUNT*>(
               &_RES_CREATE_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RES_CREATE_ACCOUNT& a, RES_CREATE_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(RES_CREATE_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RES_CREATE_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RES_CREATE_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RES_CREATE_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RES_CREATE_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RES_CREATE_ACCOUNT& from) {
    RES_CREATE_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RES_CREATE_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.RES_CREATE_ACCOUNT";
  }
  protected:
  explicit RES_CREATE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.RES_CREATE_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class REQ_LOGIN_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_LOGIN_ACCOUNT) */ {
 public:
  inline REQ_LOGIN_ACCOUNT() : REQ_LOGIN_ACCOUNT(nullptr) {}
  ~REQ_LOGIN_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR REQ_LOGIN_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_LOGIN_ACCOUNT(const REQ_LOGIN_ACCOUNT& from);
  REQ_LOGIN_ACCOUNT(REQ_LOGIN_ACCOUNT&& from) noexcept
    : REQ_LOGIN_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline REQ_LOGIN_ACCOUNT& operator=(const REQ_LOGIN_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_LOGIN_ACCOUNT& operator=(REQ_LOGIN_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_LOGIN_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_LOGIN_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const REQ_LOGIN_ACCOUNT*>(
               &_REQ_LOGIN_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(REQ_LOGIN_ACCOUNT& a, REQ_LOGIN_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_LOGIN_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_LOGIN_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_LOGIN_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_LOGIN_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_LOGIN_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_LOGIN_ACCOUNT& from) {
    REQ_LOGIN_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_LOGIN_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_LOGIN_ACCOUNT";
  }
  protected:
  explicit REQ_LOGIN_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountNameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string account_name = 1;
  void clear_account_name();
  const std::string& account_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_name();
  PROTOBUF_NODISCARD std::string* release_account_name();
  void set_allocated_account_name(std::string* account_name);
  private:
  const std::string& _internal_account_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_name(const std::string& value);
  std::string* _internal_mutable_account_name();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_LOGIN_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class REQ_LOGIN_GOOGLE_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT) */ {
 public:
  inline REQ_LOGIN_GOOGLE_ACCOUNT() : REQ_LOGIN_GOOGLE_ACCOUNT(nullptr) {}
  ~REQ_LOGIN_GOOGLE_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR REQ_LOGIN_GOOGLE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_LOGIN_GOOGLE_ACCOUNT(const REQ_LOGIN_GOOGLE_ACCOUNT& from);
  REQ_LOGIN_GOOGLE_ACCOUNT(REQ_LOGIN_GOOGLE_ACCOUNT&& from) noexcept
    : REQ_LOGIN_GOOGLE_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline REQ_LOGIN_GOOGLE_ACCOUNT& operator=(const REQ_LOGIN_GOOGLE_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_LOGIN_GOOGLE_ACCOUNT& operator=(REQ_LOGIN_GOOGLE_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_LOGIN_GOOGLE_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_LOGIN_GOOGLE_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const REQ_LOGIN_GOOGLE_ACCOUNT*>(
               &_REQ_LOGIN_GOOGLE_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(REQ_LOGIN_GOOGLE_ACCOUNT& a, REQ_LOGIN_GOOGLE_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_LOGIN_GOOGLE_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_LOGIN_GOOGLE_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_LOGIN_GOOGLE_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_LOGIN_GOOGLE_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_LOGIN_GOOGLE_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_LOGIN_GOOGLE_ACCOUNT& from) {
    REQ_LOGIN_GOOGLE_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_LOGIN_GOOGLE_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_LOGIN_GOOGLE_ACCOUNT";
  }
  protected:
  explicit REQ_LOGIN_GOOGLE_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAuthCodeFieldNumber = 1,
  };
  // string auth_code = 1;
  void clear_auth_code();
  const std::string& auth_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_auth_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_auth_code();
  PROTOBUF_NODISCARD std::string* release_auth_code();
  void set_allocated_auth_code(std::string* auth_code);
  private:
  const std::string& _internal_auth_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_auth_code(const std::string& value);
  std::string* _internal_mutable_auth_code();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr auth_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class RES_LOGIN_ACCOUNT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.RES_LOGIN_ACCOUNT) */ {
 public:
  inline RES_LOGIN_ACCOUNT() : RES_LOGIN_ACCOUNT(nullptr) {}
  ~RES_LOGIN_ACCOUNT() override;
  explicit PROTOBUF_CONSTEXPR RES_LOGIN_ACCOUNT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RES_LOGIN_ACCOUNT(const RES_LOGIN_ACCOUNT& from);
  RES_LOGIN_ACCOUNT(RES_LOGIN_ACCOUNT&& from) noexcept
    : RES_LOGIN_ACCOUNT() {
    *this = ::std::move(from);
  }

  inline RES_LOGIN_ACCOUNT& operator=(const RES_LOGIN_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }
  inline RES_LOGIN_ACCOUNT& operator=(RES_LOGIN_ACCOUNT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RES_LOGIN_ACCOUNT& default_instance() {
    return *internal_default_instance();
  }
  static inline const RES_LOGIN_ACCOUNT* internal_default_instance() {
    return reinterpret_cast<const RES_LOGIN_ACCOUNT*>(
               &_RES_LOGIN_ACCOUNT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(RES_LOGIN_ACCOUNT& a, RES_LOGIN_ACCOUNT& b) {
    a.Swap(&b);
  }
  inline void Swap(RES_LOGIN_ACCOUNT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RES_LOGIN_ACCOUNT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RES_LOGIN_ACCOUNT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RES_LOGIN_ACCOUNT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RES_LOGIN_ACCOUNT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RES_LOGIN_ACCOUNT& from) {
    RES_LOGIN_ACCOUNT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RES_LOGIN_ACCOUNT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.RES_LOGIN_ACCOUNT";
  }
  protected:
  explicit RES_LOGIN_ACCOUNT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerListFieldNumber = 4,
    kTokenValueFieldNumber = 3,
    kSuccessFieldNumber = 1,
    kAccountIdFieldNumber = 2,
  };
  // repeated .Protocol.ServerSelectInfo server_list = 4;
  int server_list_size() const;
  private:
  int _internal_server_list_size() const;
  public:
  void clear_server_list();
  ::Protocol::ServerSelectInfo* mutable_server_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >*
      mutable_server_list();
  private:
  const ::Protocol::ServerSelectInfo& _internal_server_list(int index) const;
  ::Protocol::ServerSelectInfo* _internal_add_server_list();
  public:
  const ::Protocol::ServerSelectInfo& server_list(int index) const;
  ::Protocol::ServerSelectInfo* add_server_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >&
      server_list() const;

  // string token_value = 3;
  void clear_token_value();
  const std::string& token_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token_value();
  PROTOBUF_NODISCARD std::string* release_token_value();
  void set_allocated_token_value(std::string* token_value);
  private:
  const std::string& _internal_token_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token_value(const std::string& value);
  std::string* _internal_mutable_token_value();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 account_id = 2;
  void clear_account_id();
  int32_t account_id() const;
  void set_account_id(int32_t value);
  private:
  int32_t _internal_account_id() const;
  void _internal_set_account_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.RES_LOGIN_ACCOUNT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo > server_list_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_value_;
    bool success_;
    int32_t account_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class REQ_CONNECT_GAME_SERVER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_CONNECT_GAME_SERVER) */ {
 public:
  inline REQ_CONNECT_GAME_SERVER() : REQ_CONNECT_GAME_SERVER(nullptr) {}
  ~REQ_CONNECT_GAME_SERVER() override;
  explicit PROTOBUF_CONSTEXPR REQ_CONNECT_GAME_SERVER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_CONNECT_GAME_SERVER(const REQ_CONNECT_GAME_SERVER& from);
  REQ_CONNECT_GAME_SERVER(REQ_CONNECT_GAME_SERVER&& from) noexcept
    : REQ_CONNECT_GAME_SERVER() {
    *this = ::std::move(from);
  }

  inline REQ_CONNECT_GAME_SERVER& operator=(const REQ_CONNECT_GAME_SERVER& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_CONNECT_GAME_SERVER& operator=(REQ_CONNECT_GAME_SERVER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_CONNECT_GAME_SERVER& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_CONNECT_GAME_SERVER* internal_default_instance() {
    return reinterpret_cast<const REQ_CONNECT_GAME_SERVER*>(
               &_REQ_CONNECT_GAME_SERVER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(REQ_CONNECT_GAME_SERVER& a, REQ_CONNECT_GAME_SERVER& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_CONNECT_GAME_SERVER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_CONNECT_GAME_SERVER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_CONNECT_GAME_SERVER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_CONNECT_GAME_SERVER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_CONNECT_GAME_SERVER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_CONNECT_GAME_SERVER& from) {
    REQ_CONNECT_GAME_SERVER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_CONNECT_GAME_SERVER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_CONNECT_GAME_SERVER";
  }
  protected:
  explicit REQ_CONNECT_GAME_SERVER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kServerIdFieldNumber = 2,
  };
  // int32 account_id = 1;
  void clear_account_id();
  int32_t account_id() const;
  void set_account_id(int32_t value);
  private:
  int32_t _internal_account_id() const;
  void _internal_set_account_id(int32_t value);
  public:

  // int32 server_id = 2;
  void clear_server_id();
  int32_t server_id() const;
  void set_server_id(int32_t value);
  private:
  int32_t _internal_server_id() const;
  void _internal_set_server_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_CONNECT_GAME_SERVER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t account_id_;
    int32_t server_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class RES_CONNECT_GAME_SERVER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.RES_CONNECT_GAME_SERVER) */ {
 public:
  inline RES_CONNECT_GAME_SERVER() : RES_CONNECT_GAME_SERVER(nullptr) {}
  ~RES_CONNECT_GAME_SERVER() override;
  explicit PROTOBUF_CONSTEXPR RES_CONNECT_GAME_SERVER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RES_CONNECT_GAME_SERVER(const RES_CONNECT_GAME_SERVER& from);
  RES_CONNECT_GAME_SERVER(RES_CONNECT_GAME_SERVER&& from) noexcept
    : RES_CONNECT_GAME_SERVER() {
    *this = ::std::move(from);
  }

  inline RES_CONNECT_GAME_SERVER& operator=(const RES_CONNECT_GAME_SERVER& from) {
    CopyFrom(from);
    return *this;
  }
  inline RES_CONNECT_GAME_SERVER& operator=(RES_CONNECT_GAME_SERVER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RES_CONNECT_GAME_SERVER& default_instance() {
    return *internal_default_instance();
  }
  static inline const RES_CONNECT_GAME_SERVER* internal_default_instance() {
    return reinterpret_cast<const RES_CONNECT_GAME_SERVER*>(
               &_RES_CONNECT_GAME_SERVER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(RES_CONNECT_GAME_SERVER& a, RES_CONNECT_GAME_SERVER& b) {
    a.Swap(&b);
  }
  inline void Swap(RES_CONNECT_GAME_SERVER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RES_CONNECT_GAME_SERVER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RES_CONNECT_GAME_SERVER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RES_CONNECT_GAME_SERVER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RES_CONNECT_GAME_SERVER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RES_CONNECT_GAME_SERVER& from) {
    RES_CONNECT_GAME_SERVER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RES_CONNECT_GAME_SERVER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.RES_CONNECT_GAME_SERVER";
  }
  protected:
  explicit RES_CONNECT_GAME_SERVER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerInfoFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // .Protocol.ServerInfo server_info = 2;
  bool has_server_info() const;
  private:
  bool _internal_has_server_info() const;
  public:
  void clear_server_info();
  const ::Protocol::ServerInfo& server_info() const;
  PROTOBUF_NODISCARD ::Protocol::ServerInfo* release_server_info();
  ::Protocol::ServerInfo* mutable_server_info();
  void set_allocated_server_info(::Protocol::ServerInfo* server_info);
  private:
  const ::Protocol::ServerInfo& _internal_server_info() const;
  ::Protocol::ServerInfo* _internal_mutable_server_info();
  public:
  void unsafe_arena_set_allocated_server_info(
      ::Protocol::ServerInfo* server_info);
  ::Protocol::ServerInfo* unsafe_arena_release_server_info();

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.RES_CONNECT_GAME_SERVER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::ServerInfo* server_info_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class REQ_RECHECK_SERVER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.REQ_RECHECK_SERVER) */ {
 public:
  inline REQ_RECHECK_SERVER() : REQ_RECHECK_SERVER(nullptr) {}
  ~REQ_RECHECK_SERVER() override;
  explicit PROTOBUF_CONSTEXPR REQ_RECHECK_SERVER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  REQ_RECHECK_SERVER(const REQ_RECHECK_SERVER& from);
  REQ_RECHECK_SERVER(REQ_RECHECK_SERVER&& from) noexcept
    : REQ_RECHECK_SERVER() {
    *this = ::std::move(from);
  }

  inline REQ_RECHECK_SERVER& operator=(const REQ_RECHECK_SERVER& from) {
    CopyFrom(from);
    return *this;
  }
  inline REQ_RECHECK_SERVER& operator=(REQ_RECHECK_SERVER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const REQ_RECHECK_SERVER& default_instance() {
    return *internal_default_instance();
  }
  static inline const REQ_RECHECK_SERVER* internal_default_instance() {
    return reinterpret_cast<const REQ_RECHECK_SERVER*>(
               &_REQ_RECHECK_SERVER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(REQ_RECHECK_SERVER& a, REQ_RECHECK_SERVER& b) {
    a.Swap(&b);
  }
  inline void Swap(REQ_RECHECK_SERVER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(REQ_RECHECK_SERVER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  REQ_RECHECK_SERVER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<REQ_RECHECK_SERVER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const REQ_RECHECK_SERVER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const REQ_RECHECK_SERVER& from) {
    REQ_RECHECK_SERVER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(REQ_RECHECK_SERVER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.REQ_RECHECK_SERVER";
  }
  protected:
  explicit REQ_RECHECK_SERVER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
  };
  // int32 account_id = 1;
  void clear_account_id();
  int32_t account_id() const;
  void set_account_id(int32_t value);
  private:
  int32_t _internal_account_id() const;
  void _internal_set_account_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.REQ_RECHECK_SERVER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t account_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// -------------------------------------------------------------------

class RES_RECHECK_SERVER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.RES_RECHECK_SERVER) */ {
 public:
  inline RES_RECHECK_SERVER() : RES_RECHECK_SERVER(nullptr) {}
  ~RES_RECHECK_SERVER() override;
  explicit PROTOBUF_CONSTEXPR RES_RECHECK_SERVER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RES_RECHECK_SERVER(const RES_RECHECK_SERVER& from);
  RES_RECHECK_SERVER(RES_RECHECK_SERVER&& from) noexcept
    : RES_RECHECK_SERVER() {
    *this = ::std::move(from);
  }

  inline RES_RECHECK_SERVER& operator=(const RES_RECHECK_SERVER& from) {
    CopyFrom(from);
    return *this;
  }
  inline RES_RECHECK_SERVER& operator=(RES_RECHECK_SERVER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RES_RECHECK_SERVER& default_instance() {
    return *internal_default_instance();
  }
  static inline const RES_RECHECK_SERVER* internal_default_instance() {
    return reinterpret_cast<const RES_RECHECK_SERVER*>(
               &_RES_RECHECK_SERVER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(RES_RECHECK_SERVER& a, RES_RECHECK_SERVER& b) {
    a.Swap(&b);
  }
  inline void Swap(RES_RECHECK_SERVER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RES_RECHECK_SERVER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RES_RECHECK_SERVER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RES_RECHECK_SERVER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RES_RECHECK_SERVER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RES_RECHECK_SERVER& from) {
    RES_RECHECK_SERVER::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RES_RECHECK_SERVER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.RES_RECHECK_SERVER";
  }
  protected:
  explicit RES_RECHECK_SERVER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerListFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // repeated .Protocol.ServerSelectInfo server_list = 2;
  int server_list_size() const;
  private:
  int _internal_server_list_size() const;
  public:
  void clear_server_list();
  ::Protocol::ServerSelectInfo* mutable_server_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >*
      mutable_server_list();
  private:
  const ::Protocol::ServerSelectInfo& _internal_server_list(int index) const;
  ::Protocol::ServerSelectInfo* _internal_add_server_list();
  public:
  const ::Protocol::ServerSelectInfo& server_list(int index) const;
  ::Protocol::ServerSelectInfo* add_server_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >&
      server_list() const;

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.RES_RECHECK_SERVER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo > server_list_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HttpProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// REQ_CHECK_EXISTS_ACCOUNT

// string account_name = 1;
inline void REQ_CHECK_EXISTS_ACCOUNT::clear_account_name() {
  _impl_.account_name_.ClearToEmpty();
}
inline const std::string& REQ_CHECK_EXISTS_ACCOUNT::account_name() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_CHECK_EXISTS_ACCOUNT.account_name)
  return _internal_account_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_CHECK_EXISTS_ACCOUNT::set_account_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_CHECK_EXISTS_ACCOUNT.account_name)
}
inline std::string* REQ_CHECK_EXISTS_ACCOUNT::mutable_account_name() {
  std::string* _s = _internal_mutable_account_name();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_CHECK_EXISTS_ACCOUNT.account_name)
  return _s;
}
inline const std::string& REQ_CHECK_EXISTS_ACCOUNT::_internal_account_name() const {
  return _impl_.account_name_.Get();
}
inline void REQ_CHECK_EXISTS_ACCOUNT::_internal_set_account_name(const std::string& value) {
  
  _impl_.account_name_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_CHECK_EXISTS_ACCOUNT::_internal_mutable_account_name() {
  
  return _impl_.account_name_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_CHECK_EXISTS_ACCOUNT::release_account_name() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_CHECK_EXISTS_ACCOUNT.account_name)
  return _impl_.account_name_.Release();
}
inline void REQ_CHECK_EXISTS_ACCOUNT::set_allocated_account_name(std::string* account_name) {
  if (account_name != nullptr) {
    
  } else {
    
  }
  _impl_.account_name_.SetAllocated(account_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_name_.IsDefault()) {
    _impl_.account_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_CHECK_EXISTS_ACCOUNT.account_name)
}

// -------------------------------------------------------------------

// RES_CHECK_EXISTS_ACCOUNT

// bool success = 1;
inline void RES_CHECK_EXISTS_ACCOUNT::clear_success() {
  _impl_.success_ = false;
}
inline bool RES_CHECK_EXISTS_ACCOUNT::_internal_success() const {
  return _impl_.success_;
}
inline bool RES_CHECK_EXISTS_ACCOUNT::success() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_CHECK_EXISTS_ACCOUNT.success)
  return _internal_success();
}
inline void RES_CHECK_EXISTS_ACCOUNT::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RES_CHECK_EXISTS_ACCOUNT::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_CHECK_EXISTS_ACCOUNT.success)
}

// -------------------------------------------------------------------

// REQ_CREATE_ACCOUNT

// string account_name = 1;
inline void REQ_CREATE_ACCOUNT::clear_account_name() {
  _impl_.account_name_.ClearToEmpty();
}
inline const std::string& REQ_CREATE_ACCOUNT::account_name() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_CREATE_ACCOUNT.account_name)
  return _internal_account_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_CREATE_ACCOUNT::set_account_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_CREATE_ACCOUNT.account_name)
}
inline std::string* REQ_CREATE_ACCOUNT::mutable_account_name() {
  std::string* _s = _internal_mutable_account_name();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_CREATE_ACCOUNT.account_name)
  return _s;
}
inline const std::string& REQ_CREATE_ACCOUNT::_internal_account_name() const {
  return _impl_.account_name_.Get();
}
inline void REQ_CREATE_ACCOUNT::_internal_set_account_name(const std::string& value) {
  
  _impl_.account_name_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_CREATE_ACCOUNT::_internal_mutable_account_name() {
  
  return _impl_.account_name_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_CREATE_ACCOUNT::release_account_name() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_CREATE_ACCOUNT.account_name)
  return _impl_.account_name_.Release();
}
inline void REQ_CREATE_ACCOUNT::set_allocated_account_name(std::string* account_name) {
  if (account_name != nullptr) {
    
  } else {
    
  }
  _impl_.account_name_.SetAllocated(account_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_name_.IsDefault()) {
    _impl_.account_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_CREATE_ACCOUNT.account_name)
}

// string password = 2;
inline void REQ_CREATE_ACCOUNT::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& REQ_CREATE_ACCOUNT::password() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_CREATE_ACCOUNT.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_CREATE_ACCOUNT::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_CREATE_ACCOUNT.password)
}
inline std::string* REQ_CREATE_ACCOUNT::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_CREATE_ACCOUNT.password)
  return _s;
}
inline const std::string& REQ_CREATE_ACCOUNT::_internal_password() const {
  return _impl_.password_.Get();
}
inline void REQ_CREATE_ACCOUNT::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_CREATE_ACCOUNT::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_CREATE_ACCOUNT::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_CREATE_ACCOUNT.password)
  return _impl_.password_.Release();
}
inline void REQ_CREATE_ACCOUNT::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_CREATE_ACCOUNT.password)
}

// -------------------------------------------------------------------

// RES_CREATE_ACCOUNT

// bool success = 1;
inline void RES_CREATE_ACCOUNT::clear_success() {
  _impl_.success_ = false;
}
inline bool RES_CREATE_ACCOUNT::_internal_success() const {
  return _impl_.success_;
}
inline bool RES_CREATE_ACCOUNT::success() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_CREATE_ACCOUNT.success)
  return _internal_success();
}
inline void RES_CREATE_ACCOUNT::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RES_CREATE_ACCOUNT::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_CREATE_ACCOUNT.success)
}

// -------------------------------------------------------------------

// REQ_LOGIN_ACCOUNT

// string account_name = 1;
inline void REQ_LOGIN_ACCOUNT::clear_account_name() {
  _impl_.account_name_.ClearToEmpty();
}
inline const std::string& REQ_LOGIN_ACCOUNT::account_name() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_LOGIN_ACCOUNT.account_name)
  return _internal_account_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_LOGIN_ACCOUNT::set_account_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_LOGIN_ACCOUNT.account_name)
}
inline std::string* REQ_LOGIN_ACCOUNT::mutable_account_name() {
  std::string* _s = _internal_mutable_account_name();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_LOGIN_ACCOUNT.account_name)
  return _s;
}
inline const std::string& REQ_LOGIN_ACCOUNT::_internal_account_name() const {
  return _impl_.account_name_.Get();
}
inline void REQ_LOGIN_ACCOUNT::_internal_set_account_name(const std::string& value) {
  
  _impl_.account_name_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_ACCOUNT::_internal_mutable_account_name() {
  
  return _impl_.account_name_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_ACCOUNT::release_account_name() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_LOGIN_ACCOUNT.account_name)
  return _impl_.account_name_.Release();
}
inline void REQ_LOGIN_ACCOUNT::set_allocated_account_name(std::string* account_name) {
  if (account_name != nullptr) {
    
  } else {
    
  }
  _impl_.account_name_.SetAllocated(account_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_name_.IsDefault()) {
    _impl_.account_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_LOGIN_ACCOUNT.account_name)
}

// string password = 2;
inline void REQ_LOGIN_ACCOUNT::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& REQ_LOGIN_ACCOUNT::password() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_LOGIN_ACCOUNT.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_LOGIN_ACCOUNT::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_LOGIN_ACCOUNT.password)
}
inline std::string* REQ_LOGIN_ACCOUNT::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_LOGIN_ACCOUNT.password)
  return _s;
}
inline const std::string& REQ_LOGIN_ACCOUNT::_internal_password() const {
  return _impl_.password_.Get();
}
inline void REQ_LOGIN_ACCOUNT::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_ACCOUNT::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_ACCOUNT::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_LOGIN_ACCOUNT.password)
  return _impl_.password_.Release();
}
inline void REQ_LOGIN_ACCOUNT::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_LOGIN_ACCOUNT.password)
}

// -------------------------------------------------------------------

// REQ_LOGIN_GOOGLE_ACCOUNT

// string auth_code = 1;
inline void REQ_LOGIN_GOOGLE_ACCOUNT::clear_auth_code() {
  _impl_.auth_code_.ClearToEmpty();
}
inline const std::string& REQ_LOGIN_GOOGLE_ACCOUNT::auth_code() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT.auth_code)
  return _internal_auth_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void REQ_LOGIN_GOOGLE_ACCOUNT::set_auth_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.auth_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT.auth_code)
}
inline std::string* REQ_LOGIN_GOOGLE_ACCOUNT::mutable_auth_code() {
  std::string* _s = _internal_mutable_auth_code();
  // @@protoc_insertion_point(field_mutable:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT.auth_code)
  return _s;
}
inline const std::string& REQ_LOGIN_GOOGLE_ACCOUNT::_internal_auth_code() const {
  return _impl_.auth_code_.Get();
}
inline void REQ_LOGIN_GOOGLE_ACCOUNT::_internal_set_auth_code(const std::string& value) {
  
  _impl_.auth_code_.Set(value, GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_GOOGLE_ACCOUNT::_internal_mutable_auth_code() {
  
  return _impl_.auth_code_.Mutable(GetArenaForAllocation());
}
inline std::string* REQ_LOGIN_GOOGLE_ACCOUNT::release_auth_code() {
  // @@protoc_insertion_point(field_release:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT.auth_code)
  return _impl_.auth_code_.Release();
}
inline void REQ_LOGIN_GOOGLE_ACCOUNT::set_allocated_auth_code(std::string* auth_code) {
  if (auth_code != nullptr) {
    
  } else {
    
  }
  _impl_.auth_code_.SetAllocated(auth_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.auth_code_.IsDefault()) {
    _impl_.auth_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.REQ_LOGIN_GOOGLE_ACCOUNT.auth_code)
}

// -------------------------------------------------------------------

// RES_LOGIN_ACCOUNT

// bool success = 1;
inline void RES_LOGIN_ACCOUNT::clear_success() {
  _impl_.success_ = false;
}
inline bool RES_LOGIN_ACCOUNT::_internal_success() const {
  return _impl_.success_;
}
inline bool RES_LOGIN_ACCOUNT::success() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_LOGIN_ACCOUNT.success)
  return _internal_success();
}
inline void RES_LOGIN_ACCOUNT::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RES_LOGIN_ACCOUNT::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_LOGIN_ACCOUNT.success)
}

// int32 account_id = 2;
inline void RES_LOGIN_ACCOUNT::clear_account_id() {
  _impl_.account_id_ = 0;
}
inline int32_t RES_LOGIN_ACCOUNT::_internal_account_id() const {
  return _impl_.account_id_;
}
inline int32_t RES_LOGIN_ACCOUNT::account_id() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_LOGIN_ACCOUNT.account_id)
  return _internal_account_id();
}
inline void RES_LOGIN_ACCOUNT::_internal_set_account_id(int32_t value) {
  
  _impl_.account_id_ = value;
}
inline void RES_LOGIN_ACCOUNT::set_account_id(int32_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_LOGIN_ACCOUNT.account_id)
}

// string token_value = 3;
inline void RES_LOGIN_ACCOUNT::clear_token_value() {
  _impl_.token_value_.ClearToEmpty();
}
inline const std::string& RES_LOGIN_ACCOUNT::token_value() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_LOGIN_ACCOUNT.token_value)
  return _internal_token_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RES_LOGIN_ACCOUNT::set_token_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.RES_LOGIN_ACCOUNT.token_value)
}
inline std::string* RES_LOGIN_ACCOUNT::mutable_token_value() {
  std::string* _s = _internal_mutable_token_value();
  // @@protoc_insertion_point(field_mutable:Protocol.RES_LOGIN_ACCOUNT.token_value)
  return _s;
}
inline const std::string& RES_LOGIN_ACCOUNT::_internal_token_value() const {
  return _impl_.token_value_.Get();
}
inline void RES_LOGIN_ACCOUNT::_internal_set_token_value(const std::string& value) {
  
  _impl_.token_value_.Set(value, GetArenaForAllocation());
}
inline std::string* RES_LOGIN_ACCOUNT::_internal_mutable_token_value() {
  
  return _impl_.token_value_.Mutable(GetArenaForAllocation());
}
inline std::string* RES_LOGIN_ACCOUNT::release_token_value() {
  // @@protoc_insertion_point(field_release:Protocol.RES_LOGIN_ACCOUNT.token_value)
  return _impl_.token_value_.Release();
}
inline void RES_LOGIN_ACCOUNT::set_allocated_token_value(std::string* token_value) {
  if (token_value != nullptr) {
    
  } else {
    
  }
  _impl_.token_value_.SetAllocated(token_value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_value_.IsDefault()) {
    _impl_.token_value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.RES_LOGIN_ACCOUNT.token_value)
}

// repeated .Protocol.ServerSelectInfo server_list = 4;
inline int RES_LOGIN_ACCOUNT::_internal_server_list_size() const {
  return _impl_.server_list_.size();
}
inline int RES_LOGIN_ACCOUNT::server_list_size() const {
  return _internal_server_list_size();
}
inline ::Protocol::ServerSelectInfo* RES_LOGIN_ACCOUNT::mutable_server_list(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.RES_LOGIN_ACCOUNT.server_list)
  return _impl_.server_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >*
RES_LOGIN_ACCOUNT::mutable_server_list() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.RES_LOGIN_ACCOUNT.server_list)
  return &_impl_.server_list_;
}
inline const ::Protocol::ServerSelectInfo& RES_LOGIN_ACCOUNT::_internal_server_list(int index) const {
  return _impl_.server_list_.Get(index);
}
inline const ::Protocol::ServerSelectInfo& RES_LOGIN_ACCOUNT::server_list(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.RES_LOGIN_ACCOUNT.server_list)
  return _internal_server_list(index);
}
inline ::Protocol::ServerSelectInfo* RES_LOGIN_ACCOUNT::_internal_add_server_list() {
  return _impl_.server_list_.Add();
}
inline ::Protocol::ServerSelectInfo* RES_LOGIN_ACCOUNT::add_server_list() {
  ::Protocol::ServerSelectInfo* _add = _internal_add_server_list();
  // @@protoc_insertion_point(field_add:Protocol.RES_LOGIN_ACCOUNT.server_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >&
RES_LOGIN_ACCOUNT::server_list() const {
  // @@protoc_insertion_point(field_list:Protocol.RES_LOGIN_ACCOUNT.server_list)
  return _impl_.server_list_;
}

// -------------------------------------------------------------------

// REQ_CONNECT_GAME_SERVER

// int32 account_id = 1;
inline void REQ_CONNECT_GAME_SERVER::clear_account_id() {
  _impl_.account_id_ = 0;
}
inline int32_t REQ_CONNECT_GAME_SERVER::_internal_account_id() const {
  return _impl_.account_id_;
}
inline int32_t REQ_CONNECT_GAME_SERVER::account_id() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_CONNECT_GAME_SERVER.account_id)
  return _internal_account_id();
}
inline void REQ_CONNECT_GAME_SERVER::_internal_set_account_id(int32_t value) {
  
  _impl_.account_id_ = value;
}
inline void REQ_CONNECT_GAME_SERVER::set_account_id(int32_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:Protocol.REQ_CONNECT_GAME_SERVER.account_id)
}

// int32 server_id = 2;
inline void REQ_CONNECT_GAME_SERVER::clear_server_id() {
  _impl_.server_id_ = 0;
}
inline int32_t REQ_CONNECT_GAME_SERVER::_internal_server_id() const {
  return _impl_.server_id_;
}
inline int32_t REQ_CONNECT_GAME_SERVER::server_id() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_CONNECT_GAME_SERVER.server_id)
  return _internal_server_id();
}
inline void REQ_CONNECT_GAME_SERVER::_internal_set_server_id(int32_t value) {
  
  _impl_.server_id_ = value;
}
inline void REQ_CONNECT_GAME_SERVER::set_server_id(int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:Protocol.REQ_CONNECT_GAME_SERVER.server_id)
}

// -------------------------------------------------------------------

// RES_CONNECT_GAME_SERVER

// bool success = 1;
inline void RES_CONNECT_GAME_SERVER::clear_success() {
  _impl_.success_ = false;
}
inline bool RES_CONNECT_GAME_SERVER::_internal_success() const {
  return _impl_.success_;
}
inline bool RES_CONNECT_GAME_SERVER::success() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_CONNECT_GAME_SERVER.success)
  return _internal_success();
}
inline void RES_CONNECT_GAME_SERVER::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RES_CONNECT_GAME_SERVER::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_CONNECT_GAME_SERVER.success)
}

// .Protocol.ServerInfo server_info = 2;
inline bool RES_CONNECT_GAME_SERVER::_internal_has_server_info() const {
  return this != internal_default_instance() && _impl_.server_info_ != nullptr;
}
inline bool RES_CONNECT_GAME_SERVER::has_server_info() const {
  return _internal_has_server_info();
}
inline const ::Protocol::ServerInfo& RES_CONNECT_GAME_SERVER::_internal_server_info() const {
  const ::Protocol::ServerInfo* p = _impl_.server_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::ServerInfo&>(
      ::Protocol::_ServerInfo_default_instance_);
}
inline const ::Protocol::ServerInfo& RES_CONNECT_GAME_SERVER::server_info() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_CONNECT_GAME_SERVER.server_info)
  return _internal_server_info();
}
inline void RES_CONNECT_GAME_SERVER::unsafe_arena_set_allocated_server_info(
    ::Protocol::ServerInfo* server_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.server_info_);
  }
  _impl_.server_info_ = server_info;
  if (server_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.RES_CONNECT_GAME_SERVER.server_info)
}
inline ::Protocol::ServerInfo* RES_CONNECT_GAME_SERVER::release_server_info() {
  
  ::Protocol::ServerInfo* temp = _impl_.server_info_;
  _impl_.server_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::ServerInfo* RES_CONNECT_GAME_SERVER::unsafe_arena_release_server_info() {
  // @@protoc_insertion_point(field_release:Protocol.RES_CONNECT_GAME_SERVER.server_info)
  
  ::Protocol::ServerInfo* temp = _impl_.server_info_;
  _impl_.server_info_ = nullptr;
  return temp;
}
inline ::Protocol::ServerInfo* RES_CONNECT_GAME_SERVER::_internal_mutable_server_info() {
  
  if (_impl_.server_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::ServerInfo>(GetArenaForAllocation());
    _impl_.server_info_ = p;
  }
  return _impl_.server_info_;
}
inline ::Protocol::ServerInfo* RES_CONNECT_GAME_SERVER::mutable_server_info() {
  ::Protocol::ServerInfo* _msg = _internal_mutable_server_info();
  // @@protoc_insertion_point(field_mutable:Protocol.RES_CONNECT_GAME_SERVER.server_info)
  return _msg;
}
inline void RES_CONNECT_GAME_SERVER::set_allocated_server_info(::Protocol::ServerInfo* server_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.server_info_);
  }
  if (server_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(server_info));
    if (message_arena != submessage_arena) {
      server_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, server_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.server_info_ = server_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.RES_CONNECT_GAME_SERVER.server_info)
}

// -------------------------------------------------------------------

// REQ_RECHECK_SERVER

// int32 account_id = 1;
inline void REQ_RECHECK_SERVER::clear_account_id() {
  _impl_.account_id_ = 0;
}
inline int32_t REQ_RECHECK_SERVER::_internal_account_id() const {
  return _impl_.account_id_;
}
inline int32_t REQ_RECHECK_SERVER::account_id() const {
  // @@protoc_insertion_point(field_get:Protocol.REQ_RECHECK_SERVER.account_id)
  return _internal_account_id();
}
inline void REQ_RECHECK_SERVER::_internal_set_account_id(int32_t value) {
  
  _impl_.account_id_ = value;
}
inline void REQ_RECHECK_SERVER::set_account_id(int32_t value) {
  _internal_set_account_id(value);
  // @@protoc_insertion_point(field_set:Protocol.REQ_RECHECK_SERVER.account_id)
}

// -------------------------------------------------------------------

// RES_RECHECK_SERVER

// bool success = 1;
inline void RES_RECHECK_SERVER::clear_success() {
  _impl_.success_ = false;
}
inline bool RES_RECHECK_SERVER::_internal_success() const {
  return _impl_.success_;
}
inline bool RES_RECHECK_SERVER::success() const {
  // @@protoc_insertion_point(field_get:Protocol.RES_RECHECK_SERVER.success)
  return _internal_success();
}
inline void RES_RECHECK_SERVER::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RES_RECHECK_SERVER::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.RES_RECHECK_SERVER.success)
}

// repeated .Protocol.ServerSelectInfo server_list = 2;
inline int RES_RECHECK_SERVER::_internal_server_list_size() const {
  return _impl_.server_list_.size();
}
inline int RES_RECHECK_SERVER::server_list_size() const {
  return _internal_server_list_size();
}
inline ::Protocol::ServerSelectInfo* RES_RECHECK_SERVER::mutable_server_list(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.RES_RECHECK_SERVER.server_list)
  return _impl_.server_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >*
RES_RECHECK_SERVER::mutable_server_list() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.RES_RECHECK_SERVER.server_list)
  return &_impl_.server_list_;
}
inline const ::Protocol::ServerSelectInfo& RES_RECHECK_SERVER::_internal_server_list(int index) const {
  return _impl_.server_list_.Get(index);
}
inline const ::Protocol::ServerSelectInfo& RES_RECHECK_SERVER::server_list(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.RES_RECHECK_SERVER.server_list)
  return _internal_server_list(index);
}
inline ::Protocol::ServerSelectInfo* RES_RECHECK_SERVER::_internal_add_server_list() {
  return _impl_.server_list_.Add();
}
inline ::Protocol::ServerSelectInfo* RES_RECHECK_SERVER::add_server_list() {
  ::Protocol::ServerSelectInfo* _add = _internal_add_server_list();
  // @@protoc_insertion_point(field_add:Protocol.RES_RECHECK_SERVER.server_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerSelectInfo >&
RES_RECHECK_SERVER::server_list() const {
  // @@protoc_insertion_point(field_list:Protocol.RES_RECHECK_SERVER.server_list)
  return _impl_.server_list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HttpProtocol_2eproto
