// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RedisProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RedisProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RedisProtocol_2eproto;
namespace Protocol {
class R_SERVER_DATA;
struct R_SERVER_DATADefaultTypeInternal;
extern R_SERVER_DATADefaultTypeInternal _R_SERVER_DATA_default_instance_;
class R_TOKEN_DATA;
struct R_TOKEN_DATADefaultTypeInternal;
extern R_TOKEN_DATADefaultTypeInternal _R_TOKEN_DATA_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::R_SERVER_DATA* Arena::CreateMaybeMessage<::Protocol::R_SERVER_DATA>(Arena*);
template<> ::Protocol::R_TOKEN_DATA* Arena::CreateMaybeMessage<::Protocol::R_TOKEN_DATA>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class R_TOKEN_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.R_TOKEN_DATA) */ {
 public:
  inline R_TOKEN_DATA() : R_TOKEN_DATA(nullptr) {}
  ~R_TOKEN_DATA() override;
  explicit PROTOBUF_CONSTEXPR R_TOKEN_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  R_TOKEN_DATA(const R_TOKEN_DATA& from);
  R_TOKEN_DATA(R_TOKEN_DATA&& from) noexcept
    : R_TOKEN_DATA() {
    *this = ::std::move(from);
  }

  inline R_TOKEN_DATA& operator=(const R_TOKEN_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline R_TOKEN_DATA& operator=(R_TOKEN_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const R_TOKEN_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const R_TOKEN_DATA* internal_default_instance() {
    return reinterpret_cast<const R_TOKEN_DATA*>(
               &_R_TOKEN_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(R_TOKEN_DATA& a, R_TOKEN_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(R_TOKEN_DATA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(R_TOKEN_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  R_TOKEN_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<R_TOKEN_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const R_TOKEN_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const R_TOKEN_DATA& from) {
    R_TOKEN_DATA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R_TOKEN_DATA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.R_TOKEN_DATA";
  }
  protected:
  explicit R_TOKEN_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountDbIdFieldNumber = 1,
    kTokenValueFieldNumber = 2,
  };
  // int32 account_db_id = 1;
  void clear_account_db_id();
  int32_t account_db_id() const;
  void set_account_db_id(int32_t value);
  private:
  int32_t _internal_account_db_id() const;
  void _internal_set_account_db_id(int32_t value);
  public:

  // int32 token_value = 2;
  void clear_token_value();
  int32_t token_value() const;
  void set_token_value(int32_t value);
  private:
  int32_t _internal_token_value() const;
  void _internal_set_token_value(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.R_TOKEN_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t account_db_id_;
    int32_t token_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RedisProtocol_2eproto;
};
// -------------------------------------------------------------------

class R_SERVER_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.R_SERVER_DATA) */ {
 public:
  inline R_SERVER_DATA() : R_SERVER_DATA(nullptr) {}
  ~R_SERVER_DATA() override;
  explicit PROTOBUF_CONSTEXPR R_SERVER_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  R_SERVER_DATA(const R_SERVER_DATA& from);
  R_SERVER_DATA(R_SERVER_DATA&& from) noexcept
    : R_SERVER_DATA() {
    *this = ::std::move(from);
  }

  inline R_SERVER_DATA& operator=(const R_SERVER_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline R_SERVER_DATA& operator=(R_SERVER_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const R_SERVER_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const R_SERVER_DATA* internal_default_instance() {
    return reinterpret_cast<const R_SERVER_DATA*>(
               &_R_SERVER_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(R_SERVER_DATA& a, R_SERVER_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(R_SERVER_DATA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(R_SERVER_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  R_SERVER_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<R_SERVER_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const R_SERVER_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const R_SERVER_DATA& from) {
    R_SERVER_DATA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R_SERVER_DATA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.R_SERVER_DATA";
  }
  protected:
  explicit R_SERVER_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kIpAddressFieldNumber = 2,
    kPortFieldNumber = 3,
    kDensityFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string ip_address = 2;
  void clear_ip_address();
  const std::string& ip_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip_address();
  PROTOBUF_NODISCARD std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // string port = 3;
  void clear_port();
  const std::string& port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_port();
  PROTOBUF_NODISCARD std::string* release_port();
  void set_allocated_port(std::string* port);
  private:
  const std::string& _internal_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* _internal_mutable_port();
  public:

  // int32 density = 4;
  void clear_density();
  int32_t density() const;
  void set_density(int32_t value);
  private:
  int32_t _internal_density() const;
  void _internal_set_density(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.R_SERVER_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr port_;
    int32_t density_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RedisProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// R_TOKEN_DATA

// int32 account_db_id = 1;
inline void R_TOKEN_DATA::clear_account_db_id() {
  _impl_.account_db_id_ = 0;
}
inline int32_t R_TOKEN_DATA::_internal_account_db_id() const {
  return _impl_.account_db_id_;
}
inline int32_t R_TOKEN_DATA::account_db_id() const {
  // @@protoc_insertion_point(field_get:Protocol.R_TOKEN_DATA.account_db_id)
  return _internal_account_db_id();
}
inline void R_TOKEN_DATA::_internal_set_account_db_id(int32_t value) {
  
  _impl_.account_db_id_ = value;
}
inline void R_TOKEN_DATA::set_account_db_id(int32_t value) {
  _internal_set_account_db_id(value);
  // @@protoc_insertion_point(field_set:Protocol.R_TOKEN_DATA.account_db_id)
}

// int32 token_value = 2;
inline void R_TOKEN_DATA::clear_token_value() {
  _impl_.token_value_ = 0;
}
inline int32_t R_TOKEN_DATA::_internal_token_value() const {
  return _impl_.token_value_;
}
inline int32_t R_TOKEN_DATA::token_value() const {
  // @@protoc_insertion_point(field_get:Protocol.R_TOKEN_DATA.token_value)
  return _internal_token_value();
}
inline void R_TOKEN_DATA::_internal_set_token_value(int32_t value) {
  
  _impl_.token_value_ = value;
}
inline void R_TOKEN_DATA::set_token_value(int32_t value) {
  _internal_set_token_value(value);
  // @@protoc_insertion_point(field_set:Protocol.R_TOKEN_DATA.token_value)
}

// -------------------------------------------------------------------

// R_SERVER_DATA

// string name = 1;
inline void R_SERVER_DATA::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::name() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.name)
}
inline std::string* R_SERVER_DATA::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.name)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_name() const {
  return _impl_.name_.Get();
}
inline void R_SERVER_DATA::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.name)
  return _impl_.name_.Release();
}
inline void R_SERVER_DATA::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.name)
}

// string ip_address = 2;
inline void R_SERVER_DATA::clear_ip_address() {
  _impl_.ip_address_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::ip_address() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.ip_address)
  return _internal_ip_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_ip_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.ip_address)
}
inline std::string* R_SERVER_DATA::mutable_ip_address() {
  std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.ip_address)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_ip_address() const {
  return _impl_.ip_address_.Get();
}
inline void R_SERVER_DATA::_internal_set_ip_address(const std::string& value) {
  
  _impl_.ip_address_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_ip_address() {
  
  return _impl_.ip_address_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_ip_address() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.ip_address)
  return _impl_.ip_address_.Release();
}
inline void R_SERVER_DATA::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    
  } else {
    
  }
  _impl_.ip_address_.SetAllocated(ip_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.ip_address)
}

// string port = 3;
inline void R_SERVER_DATA::clear_port() {
  _impl_.port_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::port() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.port)
  return _internal_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_port(ArgT0&& arg0, ArgT... args) {
 
 _impl_.port_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.port)
}
inline std::string* R_SERVER_DATA::mutable_port() {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.port)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_port() const {
  return _impl_.port_.Get();
}
inline void R_SERVER_DATA::_internal_set_port(const std::string& value) {
  
  _impl_.port_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_port() {
  
  return _impl_.port_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_port() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.port)
  return _impl_.port_.Release();
}
inline void R_SERVER_DATA::set_allocated_port(std::string* port) {
  if (port != nullptr) {
    
  } else {
    
  }
  _impl_.port_.SetAllocated(port, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.port)
}

// int32 density = 4;
inline void R_SERVER_DATA::clear_density() {
  _impl_.density_ = 0;
}
inline int32_t R_SERVER_DATA::_internal_density() const {
  return _impl_.density_;
}
inline int32_t R_SERVER_DATA::density() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.density)
  return _internal_density();
}
inline void R_SERVER_DATA::_internal_set_density(int32_t value) {
  
  _impl_.density_ = value;
}
inline void R_SERVER_DATA::set_density(int32_t value) {
  _internal_set_density(value);
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.density)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto
