// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RedisProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RedisProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RedisProtocol_2eproto;
namespace Protocol {
class R_ACCOUNT_DATA;
struct R_ACCOUNT_DATADefaultTypeInternal;
extern R_ACCOUNT_DATADefaultTypeInternal _R_ACCOUNT_DATA_default_instance_;
class R_PLAYER_DATA;
struct R_PLAYER_DATADefaultTypeInternal;
extern R_PLAYER_DATADefaultTypeInternal _R_PLAYER_DATA_default_instance_;
class R_SERVER_DATA;
struct R_SERVER_DATADefaultTypeInternal;
extern R_SERVER_DATADefaultTypeInternal _R_SERVER_DATA_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::R_ACCOUNT_DATA* Arena::CreateMaybeMessage<::Protocol::R_ACCOUNT_DATA>(Arena*);
template<> ::Protocol::R_PLAYER_DATA* Arena::CreateMaybeMessage<::Protocol::R_PLAYER_DATA>(Arena*);
template<> ::Protocol::R_SERVER_DATA* Arena::CreateMaybeMessage<::Protocol::R_SERVER_DATA>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class R_SERVER_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.R_SERVER_DATA) */ {
 public:
  inline R_SERVER_DATA() : R_SERVER_DATA(nullptr) {}
  ~R_SERVER_DATA() override;
  explicit PROTOBUF_CONSTEXPR R_SERVER_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  R_SERVER_DATA(const R_SERVER_DATA& from);
  R_SERVER_DATA(R_SERVER_DATA&& from) noexcept
    : R_SERVER_DATA() {
    *this = ::std::move(from);
  }

  inline R_SERVER_DATA& operator=(const R_SERVER_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline R_SERVER_DATA& operator=(R_SERVER_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const R_SERVER_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const R_SERVER_DATA* internal_default_instance() {
    return reinterpret_cast<const R_SERVER_DATA*>(
               &_R_SERVER_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(R_SERVER_DATA& a, R_SERVER_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(R_SERVER_DATA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(R_SERVER_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  R_SERVER_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<R_SERVER_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const R_SERVER_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const R_SERVER_DATA& from) {
    R_SERVER_DATA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R_SERVER_DATA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.R_SERVER_DATA";
  }
  protected:
  explicit R_SERVER_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIpAddressFieldNumber = 3,
    kPortFieldNumber = 4,
    kServerIdFieldNumber = 1,
    kDensityFieldNumber = 5,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string ip_address = 3;
  void clear_ip_address();
  const std::string& ip_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip_address();
  PROTOBUF_NODISCARD std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // string port = 4;
  void clear_port();
  const std::string& port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_port();
  PROTOBUF_NODISCARD std::string* release_port();
  void set_allocated_port(std::string* port);
  private:
  const std::string& _internal_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* _internal_mutable_port();
  public:

  // uint32 server_id = 1;
  void clear_server_id();
  uint32_t server_id() const;
  void set_server_id(uint32_t value);
  private:
  uint32_t _internal_server_id() const;
  void _internal_set_server_id(uint32_t value);
  public:

  // float density = 5;
  void clear_density();
  float density() const;
  void set_density(float value);
  private:
  float _internal_density() const;
  void _internal_set_density(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.R_SERVER_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr port_;
    uint32_t server_id_;
    float density_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RedisProtocol_2eproto;
};
// -------------------------------------------------------------------

class R_PLAYER_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.R_PLAYER_DATA) */ {
 public:
  inline R_PLAYER_DATA() : R_PLAYER_DATA(nullptr) {}
  ~R_PLAYER_DATA() override;
  explicit PROTOBUF_CONSTEXPR R_PLAYER_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  R_PLAYER_DATA(const R_PLAYER_DATA& from);
  R_PLAYER_DATA(R_PLAYER_DATA&& from) noexcept
    : R_PLAYER_DATA() {
    *this = ::std::move(from);
  }

  inline R_PLAYER_DATA& operator=(const R_PLAYER_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline R_PLAYER_DATA& operator=(R_PLAYER_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const R_PLAYER_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const R_PLAYER_DATA* internal_default_instance() {
    return reinterpret_cast<const R_PLAYER_DATA*>(
               &_R_PLAYER_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(R_PLAYER_DATA& a, R_PLAYER_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(R_PLAYER_DATA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(R_PLAYER_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  R_PLAYER_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<R_PLAYER_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const R_PLAYER_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const R_PLAYER_DATA& from) {
    R_PLAYER_DATA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R_PLAYER_DATA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.R_PLAYER_DATA";
  }
  protected:
  explicit R_PLAYER_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 3,
    kCreatedTimeFieldNumber = 6,
    kPlayerDbIdFieldNumber = 1,
    kPlayerTableIdFieldNumber = 2,
    kCostumeSettingFieldNumber = 4,
    kRankScoreFieldNumber = 5,
  };
  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .google.protobuf.Timestamp created_time = 6;
  bool has_created_time() const;
  private:
  bool _internal_has_created_time() const;
  public:
  void clear_created_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_created_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_created_time();
  void set_allocated_created_time(::PROTOBUF_NAMESPACE_ID::Timestamp* created_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_created_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_created_time();
  public:
  void unsafe_arena_set_allocated_created_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* created_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_created_time();

  // int32 player_db_id = 1;
  void clear_player_db_id();
  int32_t player_db_id() const;
  void set_player_db_id(int32_t value);
  private:
  int32_t _internal_player_db_id() const;
  void _internal_set_player_db_id(int32_t value);
  public:

  // int32 player_table_id = 2;
  void clear_player_table_id();
  int32_t player_table_id() const;
  void set_player_table_id(int32_t value);
  private:
  int32_t _internal_player_table_id() const;
  void _internal_set_player_table_id(int32_t value);
  public:

  // uint32 costume_setting = 4;
  void clear_costume_setting();
  uint32_t costume_setting() const;
  void set_costume_setting(uint32_t value);
  private:
  uint32_t _internal_costume_setting() const;
  void _internal_set_costume_setting(uint32_t value);
  public:

  // int32 rank_score = 5;
  void clear_rank_score();
  int32_t rank_score() const;
  void set_rank_score(int32_t value);
  private:
  int32_t _internal_rank_score() const;
  void _internal_set_rank_score(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.R_PLAYER_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_time_;
    int32_t player_db_id_;
    int32_t player_table_id_;
    uint32_t costume_setting_;
    int32_t rank_score_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RedisProtocol_2eproto;
};
// -------------------------------------------------------------------

class R_ACCOUNT_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.R_ACCOUNT_DATA) */ {
 public:
  inline R_ACCOUNT_DATA() : R_ACCOUNT_DATA(nullptr) {}
  ~R_ACCOUNT_DATA() override;
  explicit PROTOBUF_CONSTEXPR R_ACCOUNT_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  R_ACCOUNT_DATA(const R_ACCOUNT_DATA& from);
  R_ACCOUNT_DATA(R_ACCOUNT_DATA&& from) noexcept
    : R_ACCOUNT_DATA() {
    *this = ::std::move(from);
  }

  inline R_ACCOUNT_DATA& operator=(const R_ACCOUNT_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline R_ACCOUNT_DATA& operator=(R_ACCOUNT_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const R_ACCOUNT_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const R_ACCOUNT_DATA* internal_default_instance() {
    return reinterpret_cast<const R_ACCOUNT_DATA*>(
               &_R_ACCOUNT_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(R_ACCOUNT_DATA& a, R_ACCOUNT_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(R_ACCOUNT_DATA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(R_ACCOUNT_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  R_ACCOUNT_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<R_ACCOUNT_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const R_ACCOUNT_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const R_ACCOUNT_DATA& from) {
    R_ACCOUNT_DATA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R_ACCOUNT_DATA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.R_ACCOUNT_DATA";
  }
  protected:
  explicit R_ACCOUNT_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerDatasFieldNumber = 1,
  };
  // repeated .Protocol.R_PLAYER_DATA player_datas = 1;
  int player_datas_size() const;
  private:
  int _internal_player_datas_size() const;
  public:
  void clear_player_datas();
  ::Protocol::R_PLAYER_DATA* mutable_player_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::R_PLAYER_DATA >*
      mutable_player_datas();
  private:
  const ::Protocol::R_PLAYER_DATA& _internal_player_datas(int index) const;
  ::Protocol::R_PLAYER_DATA* _internal_add_player_datas();
  public:
  const ::Protocol::R_PLAYER_DATA& player_datas(int index) const;
  ::Protocol::R_PLAYER_DATA* add_player_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::R_PLAYER_DATA >&
      player_datas() const;

  // @@protoc_insertion_point(class_scope:Protocol.R_ACCOUNT_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::R_PLAYER_DATA > player_datas_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RedisProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// R_SERVER_DATA

// uint32 server_id = 1;
inline void R_SERVER_DATA::clear_server_id() {
  _impl_.server_id_ = 0u;
}
inline uint32_t R_SERVER_DATA::_internal_server_id() const {
  return _impl_.server_id_;
}
inline uint32_t R_SERVER_DATA::server_id() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.server_id)
  return _internal_server_id();
}
inline void R_SERVER_DATA::_internal_set_server_id(uint32_t value) {
  
  _impl_.server_id_ = value;
}
inline void R_SERVER_DATA::set_server_id(uint32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.server_id)
}

// string name = 2;
inline void R_SERVER_DATA::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::name() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.name)
}
inline std::string* R_SERVER_DATA::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.name)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_name() const {
  return _impl_.name_.Get();
}
inline void R_SERVER_DATA::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.name)
  return _impl_.name_.Release();
}
inline void R_SERVER_DATA::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.name)
}

// string ip_address = 3;
inline void R_SERVER_DATA::clear_ip_address() {
  _impl_.ip_address_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::ip_address() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.ip_address)
  return _internal_ip_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_ip_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.ip_address)
}
inline std::string* R_SERVER_DATA::mutable_ip_address() {
  std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.ip_address)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_ip_address() const {
  return _impl_.ip_address_.Get();
}
inline void R_SERVER_DATA::_internal_set_ip_address(const std::string& value) {
  
  _impl_.ip_address_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_ip_address() {
  
  return _impl_.ip_address_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_ip_address() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.ip_address)
  return _impl_.ip_address_.Release();
}
inline void R_SERVER_DATA::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    
  } else {
    
  }
  _impl_.ip_address_.SetAllocated(ip_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.ip_address)
}

// string port = 4;
inline void R_SERVER_DATA::clear_port() {
  _impl_.port_.ClearToEmpty();
}
inline const std::string& R_SERVER_DATA::port() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.port)
  return _internal_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_SERVER_DATA::set_port(ArgT0&& arg0, ArgT... args) {
 
 _impl_.port_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.port)
}
inline std::string* R_SERVER_DATA::mutable_port() {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:Protocol.R_SERVER_DATA.port)
  return _s;
}
inline const std::string& R_SERVER_DATA::_internal_port() const {
  return _impl_.port_.Get();
}
inline void R_SERVER_DATA::_internal_set_port(const std::string& value) {
  
  _impl_.port_.Set(value, GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::_internal_mutable_port() {
  
  return _impl_.port_.Mutable(GetArenaForAllocation());
}
inline std::string* R_SERVER_DATA::release_port() {
  // @@protoc_insertion_point(field_release:Protocol.R_SERVER_DATA.port)
  return _impl_.port_.Release();
}
inline void R_SERVER_DATA::set_allocated_port(std::string* port) {
  if (port != nullptr) {
    
  } else {
    
  }
  _impl_.port_.SetAllocated(port, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_SERVER_DATA.port)
}

// float density = 5;
inline void R_SERVER_DATA::clear_density() {
  _impl_.density_ = 0;
}
inline float R_SERVER_DATA::_internal_density() const {
  return _impl_.density_;
}
inline float R_SERVER_DATA::density() const {
  // @@protoc_insertion_point(field_get:Protocol.R_SERVER_DATA.density)
  return _internal_density();
}
inline void R_SERVER_DATA::_internal_set_density(float value) {
  
  _impl_.density_ = value;
}
inline void R_SERVER_DATA::set_density(float value) {
  _internal_set_density(value);
  // @@protoc_insertion_point(field_set:Protocol.R_SERVER_DATA.density)
}

// -------------------------------------------------------------------

// R_PLAYER_DATA

// int32 player_db_id = 1;
inline void R_PLAYER_DATA::clear_player_db_id() {
  _impl_.player_db_id_ = 0;
}
inline int32_t R_PLAYER_DATA::_internal_player_db_id() const {
  return _impl_.player_db_id_;
}
inline int32_t R_PLAYER_DATA::player_db_id() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.player_db_id)
  return _internal_player_db_id();
}
inline void R_PLAYER_DATA::_internal_set_player_db_id(int32_t value) {
  
  _impl_.player_db_id_ = value;
}
inline void R_PLAYER_DATA::set_player_db_id(int32_t value) {
  _internal_set_player_db_id(value);
  // @@protoc_insertion_point(field_set:Protocol.R_PLAYER_DATA.player_db_id)
}

// int32 player_table_id = 2;
inline void R_PLAYER_DATA::clear_player_table_id() {
  _impl_.player_table_id_ = 0;
}
inline int32_t R_PLAYER_DATA::_internal_player_table_id() const {
  return _impl_.player_table_id_;
}
inline int32_t R_PLAYER_DATA::player_table_id() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.player_table_id)
  return _internal_player_table_id();
}
inline void R_PLAYER_DATA::_internal_set_player_table_id(int32_t value) {
  
  _impl_.player_table_id_ = value;
}
inline void R_PLAYER_DATA::set_player_table_id(int32_t value) {
  _internal_set_player_table_id(value);
  // @@protoc_insertion_point(field_set:Protocol.R_PLAYER_DATA.player_table_id)
}

// string name = 3;
inline void R_PLAYER_DATA::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& R_PLAYER_DATA::name() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void R_PLAYER_DATA::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.R_PLAYER_DATA.name)
}
inline std::string* R_PLAYER_DATA::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.R_PLAYER_DATA.name)
  return _s;
}
inline const std::string& R_PLAYER_DATA::_internal_name() const {
  return _impl_.name_.Get();
}
inline void R_PLAYER_DATA::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* R_PLAYER_DATA::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* R_PLAYER_DATA::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.R_PLAYER_DATA.name)
  return _impl_.name_.Release();
}
inline void R_PLAYER_DATA::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_PLAYER_DATA.name)
}

// uint32 costume_setting = 4;
inline void R_PLAYER_DATA::clear_costume_setting() {
  _impl_.costume_setting_ = 0u;
}
inline uint32_t R_PLAYER_DATA::_internal_costume_setting() const {
  return _impl_.costume_setting_;
}
inline uint32_t R_PLAYER_DATA::costume_setting() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.costume_setting)
  return _internal_costume_setting();
}
inline void R_PLAYER_DATA::_internal_set_costume_setting(uint32_t value) {
  
  _impl_.costume_setting_ = value;
}
inline void R_PLAYER_DATA::set_costume_setting(uint32_t value) {
  _internal_set_costume_setting(value);
  // @@protoc_insertion_point(field_set:Protocol.R_PLAYER_DATA.costume_setting)
}

// int32 rank_score = 5;
inline void R_PLAYER_DATA::clear_rank_score() {
  _impl_.rank_score_ = 0;
}
inline int32_t R_PLAYER_DATA::_internal_rank_score() const {
  return _impl_.rank_score_;
}
inline int32_t R_PLAYER_DATA::rank_score() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.rank_score)
  return _internal_rank_score();
}
inline void R_PLAYER_DATA::_internal_set_rank_score(int32_t value) {
  
  _impl_.rank_score_ = value;
}
inline void R_PLAYER_DATA::set_rank_score(int32_t value) {
  _internal_set_rank_score(value);
  // @@protoc_insertion_point(field_set:Protocol.R_PLAYER_DATA.rank_score)
}

// .google.protobuf.Timestamp created_time = 6;
inline bool R_PLAYER_DATA::_internal_has_created_time() const {
  return this != internal_default_instance() && _impl_.created_time_ != nullptr;
}
inline bool R_PLAYER_DATA::has_created_time() const {
  return _internal_has_created_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& R_PLAYER_DATA::_internal_created_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.created_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& R_PLAYER_DATA::created_time() const {
  // @@protoc_insertion_point(field_get:Protocol.R_PLAYER_DATA.created_time)
  return _internal_created_time();
}
inline void R_PLAYER_DATA::unsafe_arena_set_allocated_created_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_time_);
  }
  _impl_.created_time_ = created_time;
  if (created_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.R_PLAYER_DATA.created_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* R_PLAYER_DATA::release_created_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_time_;
  _impl_.created_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* R_PLAYER_DATA::unsafe_arena_release_created_time() {
  // @@protoc_insertion_point(field_release:Protocol.R_PLAYER_DATA.created_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_time_;
  _impl_.created_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* R_PLAYER_DATA::_internal_mutable_created_time() {
  
  if (_impl_.created_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.created_time_ = p;
  }
  return _impl_.created_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* R_PLAYER_DATA::mutable_created_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_created_time();
  // @@protoc_insertion_point(field_mutable:Protocol.R_PLAYER_DATA.created_time)
  return _msg;
}
inline void R_PLAYER_DATA::set_allocated_created_time(::PROTOBUF_NAMESPACE_ID::Timestamp* created_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_time_);
  }
  if (created_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(created_time));
    if (message_arena != submessage_arena) {
      created_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, created_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.created_time_ = created_time;
  // @@protoc_insertion_point(field_set_allocated:Protocol.R_PLAYER_DATA.created_time)
}

// -------------------------------------------------------------------

// R_ACCOUNT_DATA

// repeated .Protocol.R_PLAYER_DATA player_datas = 1;
inline int R_ACCOUNT_DATA::_internal_player_datas_size() const {
  return _impl_.player_datas_.size();
}
inline int R_ACCOUNT_DATA::player_datas_size() const {
  return _internal_player_datas_size();
}
inline void R_ACCOUNT_DATA::clear_player_datas() {
  _impl_.player_datas_.Clear();
}
inline ::Protocol::R_PLAYER_DATA* R_ACCOUNT_DATA::mutable_player_datas(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.R_ACCOUNT_DATA.player_datas)
  return _impl_.player_datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::R_PLAYER_DATA >*
R_ACCOUNT_DATA::mutable_player_datas() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.R_ACCOUNT_DATA.player_datas)
  return &_impl_.player_datas_;
}
inline const ::Protocol::R_PLAYER_DATA& R_ACCOUNT_DATA::_internal_player_datas(int index) const {
  return _impl_.player_datas_.Get(index);
}
inline const ::Protocol::R_PLAYER_DATA& R_ACCOUNT_DATA::player_datas(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.R_ACCOUNT_DATA.player_datas)
  return _internal_player_datas(index);
}
inline ::Protocol::R_PLAYER_DATA* R_ACCOUNT_DATA::_internal_add_player_datas() {
  return _impl_.player_datas_.Add();
}
inline ::Protocol::R_PLAYER_DATA* R_ACCOUNT_DATA::add_player_datas() {
  ::Protocol::R_PLAYER_DATA* _add = _internal_add_player_datas();
  // @@protoc_insertion_point(field_add:Protocol.R_ACCOUNT_DATA.player_datas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::R_PLAYER_DATA >&
R_ACCOUNT_DATA::player_datas() const {
  // @@protoc_insertion_point(field_list:Protocol.R_ACCOUNT_DATA.player_datas)
  return _impl_.player_datas_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RedisProtocol_2eproto
