// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisProtocol.proto

#include "RedisProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR R_ACCOUNT_DATA::R_ACCOUNT_DATA(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.object_infos_)*/{}
  , /*decltype(_impl_.account_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct R_ACCOUNT_DATADefaultTypeInternal {
  PROTOBUF_CONSTEXPR R_ACCOUNT_DATADefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~R_ACCOUNT_DATADefaultTypeInternal() {}
  union {
    R_ACCOUNT_DATA _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 R_ACCOUNT_DATADefaultTypeInternal _R_ACCOUNT_DATA_default_instance_;
PROTOBUF_CONSTEXPR R_SERVER_DATA::R_SERVER_DATA(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ip_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0u
  , /*decltype(_impl_.density_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct R_SERVER_DATADefaultTypeInternal {
  PROTOBUF_CONSTEXPR R_SERVER_DATADefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~R_SERVER_DATADefaultTypeInternal() {}
  union {
    R_SERVER_DATA _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 R_SERVER_DATADefaultTypeInternal _R_SERVER_DATA_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_RedisProtocol_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_RedisProtocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_RedisProtocol_2eproto = nullptr;

const uint32_t TableStruct_RedisProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::R_ACCOUNT_DATA, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::R_ACCOUNT_DATA, _impl_.account_id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::R_ACCOUNT_DATA, _impl_.object_infos_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _impl_.ip_address_),
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::Protocol::R_SERVER_DATA, _impl_.density_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::R_ACCOUNT_DATA)},
  { 8, -1, -1, sizeof(::Protocol::R_SERVER_DATA)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_R_ACCOUNT_DATA_default_instance_._instance,
  &::Protocol::_R_SERVER_DATA_default_instance_._instance,
};

const char descriptor_table_protodef_RedisProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023RedisProtocol.proto\022\010Protocol\032\037google/"
  "protobuf/timestamp.proto\032\nEnum.proto\032\014St"
  "ruct.proto\"P\n\016R_ACCOUNT_DATA\022\022\n\naccount_"
  "id\030\001 \001(\005\022*\n\014object_infos\030\002 \003(\0132\024.Protoco"
  "l.ObjectInfo\"\\\n\rR_SERVER_DATA\022\n\n\002id\030\001 \001("
  "\r\022\014\n\004name\030\002 \001(\t\022\022\n\nip_address\030\003 \001(\t\022\014\n\004p"
  "ort\030\004 \001(\t\022\017\n\007density\030\005 \001(\002B \252\002\035Google.Pr"
  "otobuf.RedisProtocolb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_RedisProtocol_2eproto_deps[3] = {
  &::descriptor_table_Enum_2eproto,
  &::descriptor_table_Struct_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_RedisProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RedisProtocol_2eproto = {
    false, false, 308, descriptor_table_protodef_RedisProtocol_2eproto,
    "RedisProtocol.proto",
    &descriptor_table_RedisProtocol_2eproto_once, descriptor_table_RedisProtocol_2eproto_deps, 3, 2,
    schemas, file_default_instances, TableStruct_RedisProtocol_2eproto::offsets,
    file_level_metadata_RedisProtocol_2eproto, file_level_enum_descriptors_RedisProtocol_2eproto,
    file_level_service_descriptors_RedisProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RedisProtocol_2eproto_getter() {
  return &descriptor_table_RedisProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RedisProtocol_2eproto(&descriptor_table_RedisProtocol_2eproto);
namespace Protocol {

// ===================================================================

class R_ACCOUNT_DATA::_Internal {
 public:
};

void R_ACCOUNT_DATA::clear_object_infos() {
  _impl_.object_infos_.Clear();
}
R_ACCOUNT_DATA::R_ACCOUNT_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.R_ACCOUNT_DATA)
}
R_ACCOUNT_DATA::R_ACCOUNT_DATA(const R_ACCOUNT_DATA& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  R_ACCOUNT_DATA* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.object_infos_){from._impl_.object_infos_}
    , decltype(_impl_.account_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.account_id_ = from._impl_.account_id_;
  // @@protoc_insertion_point(copy_constructor:Protocol.R_ACCOUNT_DATA)
}

inline void R_ACCOUNT_DATA::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.object_infos_){arena}
    , decltype(_impl_.account_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

R_ACCOUNT_DATA::~R_ACCOUNT_DATA() {
  // @@protoc_insertion_point(destructor:Protocol.R_ACCOUNT_DATA)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void R_ACCOUNT_DATA::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.object_infos_.~RepeatedPtrField();
}

void R_ACCOUNT_DATA::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void R_ACCOUNT_DATA::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.R_ACCOUNT_DATA)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.object_infos_.Clear();
  _impl_.account_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* R_ACCOUNT_DATA::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 account_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.account_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .Protocol.ObjectInfo object_infos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_object_infos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* R_ACCOUNT_DATA::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.R_ACCOUNT_DATA)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 account_id = 1;
  if (this->_internal_account_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_account_id(), target);
  }

  // repeated .Protocol.ObjectInfo object_infos = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_object_infos_size()); i < n; i++) {
    const auto& repfield = this->_internal_object_infos(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.R_ACCOUNT_DATA)
  return target;
}

size_t R_ACCOUNT_DATA::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.R_ACCOUNT_DATA)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Protocol.ObjectInfo object_infos = 2;
  total_size += 1UL * this->_internal_object_infos_size();
  for (const auto& msg : this->_impl_.object_infos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 account_id = 1;
  if (this->_internal_account_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_account_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData R_ACCOUNT_DATA::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    R_ACCOUNT_DATA::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*R_ACCOUNT_DATA::GetClassData() const { return &_class_data_; }


void R_ACCOUNT_DATA::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<R_ACCOUNT_DATA*>(&to_msg);
  auto& from = static_cast<const R_ACCOUNT_DATA&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.R_ACCOUNT_DATA)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.object_infos_.MergeFrom(from._impl_.object_infos_);
  if (from._internal_account_id() != 0) {
    _this->_internal_set_account_id(from._internal_account_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void R_ACCOUNT_DATA::CopyFrom(const R_ACCOUNT_DATA& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.R_ACCOUNT_DATA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool R_ACCOUNT_DATA::IsInitialized() const {
  return true;
}

void R_ACCOUNT_DATA::InternalSwap(R_ACCOUNT_DATA* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.object_infos_.InternalSwap(&other->_impl_.object_infos_);
  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata R_ACCOUNT_DATA::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RedisProtocol_2eproto_getter, &descriptor_table_RedisProtocol_2eproto_once,
      file_level_metadata_RedisProtocol_2eproto[0]);
}

// ===================================================================

class R_SERVER_DATA::_Internal {
 public:
};

R_SERVER_DATA::R_SERVER_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.R_SERVER_DATA)
}
R_SERVER_DATA::R_SERVER_DATA(const R_SERVER_DATA& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  R_SERVER_DATA* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.density_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip_address().empty()) {
    _this->_impl_.ip_address_.Set(from._internal_ip_address(), 
      _this->GetArenaForAllocation());
  }
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_port().empty()) {
    _this->_impl_.port_.Set(from._internal_port(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.density_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.density_));
  // @@protoc_insertion_point(copy_constructor:Protocol.R_SERVER_DATA)
}

inline void R_SERVER_DATA::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.id_){0u}
    , decltype(_impl_.density_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

R_SERVER_DATA::~R_SERVER_DATA() {
  // @@protoc_insertion_point(destructor:Protocol.R_SERVER_DATA)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void R_SERVER_DATA::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.ip_address_.Destroy();
  _impl_.port_.Destroy();
}

void R_SERVER_DATA::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void R_SERVER_DATA::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.R_SERVER_DATA)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.ip_address_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.density_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.density_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* R_SERVER_DATA::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.R_SERVER_DATA.name"));
        } else
          goto handle_unusual;
        continue;
      // string ip_address = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.R_SERVER_DATA.ip_address"));
        } else
          goto handle_unusual;
        continue;
      // string port = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_port();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.R_SERVER_DATA.port"));
        } else
          goto handle_unusual;
        continue;
      // float density = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.density_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* R_SERVER_DATA::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.R_SERVER_DATA)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.R_SERVER_DATA.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // string ip_address = 3;
  if (!this->_internal_ip_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.R_SERVER_DATA.ip_address");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_ip_address(), target);
  }

  // string port = 4;
  if (!this->_internal_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_port().data(), static_cast<int>(this->_internal_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.R_SERVER_DATA.port");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_port(), target);
  }

  // float density = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_density = this->_internal_density();
  uint32_t raw_density;
  memcpy(&raw_density, &tmp_density, sizeof(tmp_density));
  if (raw_density != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_density(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.R_SERVER_DATA)
  return target;
}

size_t R_SERVER_DATA::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.R_SERVER_DATA)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string ip_address = 3;
  if (!this->_internal_ip_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip_address());
  }

  // string port = 4;
  if (!this->_internal_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());
  }

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_id());
  }

  // float density = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_density = this->_internal_density();
  uint32_t raw_density;
  memcpy(&raw_density, &tmp_density, sizeof(tmp_density));
  if (raw_density != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData R_SERVER_DATA::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    R_SERVER_DATA::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*R_SERVER_DATA::GetClassData() const { return &_class_data_; }


void R_SERVER_DATA::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<R_SERVER_DATA*>(&to_msg);
  auto& from = static_cast<const R_SERVER_DATA&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.R_SERVER_DATA)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_ip_address().empty()) {
    _this->_internal_set_ip_address(from._internal_ip_address());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_density = from._internal_density();
  uint32_t raw_density;
  memcpy(&raw_density, &tmp_density, sizeof(tmp_density));
  if (raw_density != 0) {
    _this->_internal_set_density(from._internal_density());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void R_SERVER_DATA::CopyFrom(const R_SERVER_DATA& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.R_SERVER_DATA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool R_SERVER_DATA::IsInitialized() const {
  return true;
}

void R_SERVER_DATA::InternalSwap(R_SERVER_DATA* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_address_, lhs_arena,
      &other->_impl_.ip_address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.port_, lhs_arena,
      &other->_impl_.port_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(R_SERVER_DATA, _impl_.density_)
      + sizeof(R_SERVER_DATA::_impl_.density_)
      - PROTOBUF_FIELD_OFFSET(R_SERVER_DATA, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata R_SERVER_DATA::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RedisProtocol_2eproto_getter, &descriptor_table_RedisProtocol_2eproto_once,
      file_level_metadata_RedisProtocol_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::R_ACCOUNT_DATA*
Arena::CreateMaybeMessage< ::Protocol::R_ACCOUNT_DATA >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::R_ACCOUNT_DATA >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::R_SERVER_DATA*
Arena::CreateMaybeMessage< ::Protocol::R_SERVER_DATA >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::R_SERVER_DATA >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
