// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbBofZ29vZ2xlL3Byb3RvYnVmL3RpbWVz",
            "dGFtcC5wcm90byp+CgpPYmplY3RUeXBlEhQKEE9CSkVDVF9UWVBFX05PTkUQ",
            "ABITCg9PQkpFQ1RfVFlQRV9FTlYQARIUChBPQkpFQ1RfVFlQRV9CQUxMEAIS",
            "FwoTT0JKRUNUX1RZUEVfQVRITEVURRADEhYKEk9CSkVDVF9UWVBFX1BMQVlF",
            "UhAEKmMKCFJvb21UeXBlEhIKDlJPT01fVFlQRV9OT05FEAASEwoPUk9PTV9U",
            "WVBFX0xPQkJZEAESFQoRUk9PTV9UWVBFX01FRVRJTkcQAhIXChNST09NX1RZ",
            "UEVfVEVBTU1BVENIEAMqgwEKC0F0aGxldGVSYWNlEhUKEUFUSExFVEVfUkFD",
            "RV9OT05FEAASFgoSQVRITEVURV9SQUNFX0hVTUFOEAESFgoSQVRITEVURV9S",
            "QUNFX1NMSU1FEAISFwoTQVRITEVURV9SQUNFX0dFQVJPThADEhQKEEFUSExF",
            "VEVfUkFDRV9ST08QBCqDAQoPQXRobGV0ZVBvc2l0aW9uEhkKFUFUSExFVEVf",
            "UE9TSVRJT05fTk9ORRAAEhwKGEFUSExFVEVfUE9TSVRJT05fRk9SV0FSRBAB",
            "EhoKFkFUSExFVEVfUE9TSVRJT05fR1VBUkQQAhIbChdBVEhMRVRFX1BPU0lU",
            "SU9OX0NFTlRFUhADKiIKCkF0aGxldGVUYWcSFAoQQVRITEVURV9UQUdfTk9O",
            "RRAAKsQBCgxFbW90aW9uU3RhdGUSFgoSRU1PVElPTl9TVEFURV9OT05FEAAS",
            "GAoURU1PVElPTl9TVEFURV9OT1JNQUwQARIbChdFTU9USU9OX1NUQVRFX0NP",
            "TkZJREVOVBACEhcKE0VNT1RJT05fU1RBVEVfQU5HUlkQAxIaChZFTU9USU9O",
            "X1NUQVRFX0lOU0VDVVJFEAQSGAoURU1PVElPTl9TVEFURV9SVVNIRUQQBRIW",
            "ChJFTU9USU9OX1NUQVRFX0hVUlQQBipqCgpJbmp1cnlUeXBlEhQKEElOSlVS",
            "WV9UWVBFX05PTkUQABIWChJJTkpVUllfVFlQRV9TUFJBSU4QARIUChBJTkpV",
            "UllfVFlQRV9URUFSEAISGAoUSU5KVVJZX1RZUEVfRlJBQ1RVUkUQAyp8CghC",
            "b2R5cGFydBIRCg1CT0RZUEFSVF9OT05FEAASEgoOQk9EWVBBUlRfQU5LTEUQ",
            "ARIQCgxCT0RZUEFSVF9MRUcQAhIRCg1CT0RZUEFSVF9LTkVFEAMSEQoNQk9E",
            "WVBBUlRfQkFDSxAEEhEKDUJPRFlQQVJUX0hBTkQQBSrmAQoJTW92ZVN0YXRl",
            "EhMKD01PVkVfU1RBVEVfTk9ORRAAEhMKD01PVkVfU1RBVEVfSURMRRABEhMK",
            "D01PVkVfU1RBVEVfV0FMSxACEhYKEk1PVkVfU1RBVEVfUEhZU0lDUxADEhoK",
            "Fk1PVkVfU1RBVEVfRk9MTE9XX1BBVEgQBBISCg5NT1ZFX1NUQVRFX1JVThAF",
            "EhMKD01PVkVfU1RBVEVfSlVNUBAGEhQKEE1PVkVfU1RBVEVfU1RFQUwQBxIS",
            "Cg5NT1ZFX1NUQVRFX0hJVBAIEhMKD01PVkVfU1RBVEVfSFVSVBAJKpUBCglU",
            "ZWFtU3RhdGUSEwoPVEVBTV9TVEFURV9OT05FEAASFgoSVEVBTV9TVEFURV9P",
            "RkZFTlNFEAESFgoSVEVBTV9TVEFURV9ERUZFTlNFEAISGQoVVEVBTV9TVEFU",
            "RV9MT09TRV9CQUxMEAMSFAoQVEVBTV9TVEFURV9CUkVBSxAEEhIKDlRFQU1f",
            "U1RBVEVfRU5EEAUqJAoLVGFjdGljc1R5cGUSFQoRVEFDVElDU19UWVBFX05P",
            "TkUQACqXAQoNVGVhbU1hdGNoVHlwZRIYChRURUFNX01BVENIX1RZUEVfTk9O",
            "RRAAEhoKFlRFQU1fTUFUQ0hfVFlQRV9TRUFTT04QARIYChRURUFNX01BVENI",
            "X1RZUEVfRlJFRRACEhsKF1RFQU1fTUFUQ0hfVFlQRV9QTEFZT0ZGEAMSGQoV",
            "VEVBTV9NQVRDSF9UWVBFX0ZJTkFMEARCF6oCFEdvb2dsZS5Qcm90b2J1Zi5F",
            "bnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.ObjectType), typeof(global::Google.Protobuf.Enum.RoomType), typeof(global::Google.Protobuf.Enum.AthleteRace), typeof(global::Google.Protobuf.Enum.AthletePosition), typeof(global::Google.Protobuf.Enum.AthleteTag), typeof(global::Google.Protobuf.Enum.EmotionState), typeof(global::Google.Protobuf.Enum.InjuryType), typeof(global::Google.Protobuf.Enum.Bodypart), typeof(global::Google.Protobuf.Enum.MoveState), typeof(global::Google.Protobuf.Enum.TeamState), typeof(global::Google.Protobuf.Enum.TacticsType), typeof(global::Google.Protobuf.Enum.TeamMatchType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_ENV")] Env = 1,
    [pbr::OriginalName("OBJECT_TYPE_BALL")] Ball = 2,
    [pbr::OriginalName("OBJECT_TYPE_ATHLETE")] Athlete = 3,
    [pbr::OriginalName("OBJECT_TYPE_PLAYER")] Player = 4,
  }

  public enum RoomType {
    [pbr::OriginalName("ROOM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ROOM_TYPE_LOBBY")] Lobby = 1,
    [pbr::OriginalName("ROOM_TYPE_MEETING")] Meeting = 2,
    [pbr::OriginalName("ROOM_TYPE_TEAMMATCH")] Teammatch = 3,
  }

  public enum AthleteRace {
    [pbr::OriginalName("ATHLETE_RACE_NONE")] None = 0,
    [pbr::OriginalName("ATHLETE_RACE_HUMAN")] Human = 1,
    [pbr::OriginalName("ATHLETE_RACE_SLIME")] Slime = 2,
    [pbr::OriginalName("ATHLETE_RACE_GEARON")] Gearon = 3,
    [pbr::OriginalName("ATHLETE_RACE_ROO")] Roo = 4,
  }

  /// <summary>
  /// 선수 메인 포지션 정보
  /// </summary>
  public enum AthletePosition {
    [pbr::OriginalName("ATHLETE_POSITION_NONE")] None = 0,
    [pbr::OriginalName("ATHLETE_POSITION_FORWARD")] Forward = 1,
    [pbr::OriginalName("ATHLETE_POSITION_GUARD")] Guard = 2,
    [pbr::OriginalName("ATHLETE_POSITION_CENTER")] Center = 3,
  }

  /// <summary>
  /// 선수의 성장에 영향을 주는 속성
  /// </summary>
  public enum AthleteTag {
    [pbr::OriginalName("ATHLETE_TAG_NONE")] None = 0,
  }

  public enum EmotionState {
    [pbr::OriginalName("EMOTION_STATE_NONE")] None = 0,
    [pbr::OriginalName("EMOTION_STATE_NORMAL")] Normal = 1,
    [pbr::OriginalName("EMOTION_STATE_CONFIDENT")] Confident = 2,
    [pbr::OriginalName("EMOTION_STATE_ANGRY")] Angry = 3,
    [pbr::OriginalName("EMOTION_STATE_INSECURE")] Insecure = 4,
    [pbr::OriginalName("EMOTION_STATE_RUSHED")] Rushed = 5,
    [pbr::OriginalName("EMOTION_STATE_HURT")] Hurt = 6,
  }

  public enum InjuryType {
    [pbr::OriginalName("INJURY_TYPE_NONE")] None = 0,
    [pbr::OriginalName("INJURY_TYPE_SPRAIN")] Sprain = 1,
    [pbr::OriginalName("INJURY_TYPE_TEAR")] Tear = 2,
    [pbr::OriginalName("INJURY_TYPE_FRACTURE")] Fracture = 3,
  }

  public enum Bodypart {
    [pbr::OriginalName("BODYPART_NONE")] None = 0,
    [pbr::OriginalName("BODYPART_ANKLE")] Ankle = 1,
    [pbr::OriginalName("BODYPART_LEG")] Leg = 2,
    [pbr::OriginalName("BODYPART_KNEE")] Knee = 3,
    [pbr::OriginalName("BODYPART_BACK")] Back = 4,
    [pbr::OriginalName("BODYPART_HAND")] Hand = 5,
  }

  /// <summary>
  /// 공용 State
  /// </summary>
  public enum MoveState {
    [pbr::OriginalName("MOVE_STATE_NONE")] None = 0,
    [pbr::OriginalName("MOVE_STATE_IDLE")] Idle = 1,
    [pbr::OriginalName("MOVE_STATE_WALK")] Walk = 2,
    [pbr::OriginalName("MOVE_STATE_PHYSICS")] Physics = 3,
    [pbr::OriginalName("MOVE_STATE_FOLLOW_PATH")] FollowPath = 4,
    [pbr::OriginalName("MOVE_STATE_RUN")] Run = 5,
    [pbr::OriginalName("MOVE_STATE_JUMP")] Jump = 6,
    [pbr::OriginalName("MOVE_STATE_STEAL")] Steal = 7,
    [pbr::OriginalName("MOVE_STATE_HIT")] Hit = 8,
    [pbr::OriginalName("MOVE_STATE_HURT")] Hurt = 9,
  }

  public enum TeamState {
    [pbr::OriginalName("TEAM_STATE_NONE")] None = 0,
    [pbr::OriginalName("TEAM_STATE_OFFENSE")] Offense = 1,
    [pbr::OriginalName("TEAM_STATE_DEFENSE")] Defense = 2,
    [pbr::OriginalName("TEAM_STATE_LOOSE_BALL")] LooseBall = 3,
    [pbr::OriginalName("TEAM_STATE_BREAK")] Break = 4,
    [pbr::OriginalName("TEAM_STATE_END")] End = 5,
  }

  public enum TacticsType {
    [pbr::OriginalName("TACTICS_TYPE_NONE")] None = 0,
  }

  public enum TeamMatchType {
    [pbr::OriginalName("TEAM_MATCH_TYPE_NONE")] None = 0,
    [pbr::OriginalName("TEAM_MATCH_TYPE_SEASON")] Season = 1,
    [pbr::OriginalName("TEAM_MATCH_TYPE_FREE")] Free = 2,
    [pbr::OriginalName("TEAM_MATCH_TYPE_PLAYOFF")] Playoff = 3,
    [pbr::OriginalName("TEAM_MATCH_TYPE_FINAL")] Final = 4,
  }

  #endregion

}

#endregion Designer generated code
