// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WS_SB.DB;

#nullable disable

namespace WS_SB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250310202233_CreateLoginFlow")]
    partial class CreateLoginFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.Property<int>("AccountDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountDBId"));

                    b.Property<string>("AccountSnsSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SnsSub");

                    b.Property<int>("AccountSnsType")
                        .HasColumnType("int")
                        .HasColumnName("SnsType");

                    b.Property<int?>("RegisterDBId")
                        .HasColumnType("int");

                    b.HasKey("AccountDBId");

                    b.HasIndex("RegisterDBId")
                        .IsUnique()
                        .HasFilter("[RegisterDBId] IS NOT NULL");

                    b.HasIndex("AccountSnsType", "AccountSnsSub")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("WS_SB.DB.PlayerDB", b =>
                {
                    b.Property<int>("PlayerDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerDBId"));

                    b.Property<int>("AccountDBId")
                        .HasColumnType("int");

                    b.Property<int>("CostumeSetting")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("PlayerDBId");

                    b.HasIndex("AccountDBId");

                    b.HasIndex("Score")
                        .HasFilter("[Score] > 500");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("WS_SB.DB.RegisterDB", b =>
                {
                    b.Property<int>("RegisterDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterDBId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("RegisterDBId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.HasOne("WS_SB.DB.RegisterDB", "Register")
                        .WithOne("Account")
                        .HasForeignKey("WS_SB.DB.AccountDB", "RegisterDBId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Register");
                });

            modelBuilder.Entity("WS_SB.DB.PlayerDB", b =>
                {
                    b.HasOne("WS_SB.DB.AccountDB", null)
                        .WithMany("Players")
                        .HasForeignKey("AccountDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WS_SB.DB.RegisterDB", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
