// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WS_SB.DB;

#nullable disable

namespace WS_SB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.Property<int>("AccountDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountDBId"));

                    b.Property<string>("AccountSnsSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SnsSub");

                    b.Property<int>("AccountSnsType")
                        .HasColumnType("int")
                        .HasColumnName("SnsType");

                    b.Property<int?>("RegisterDBId")
                        .HasColumnType("int");

                    b.HasKey("AccountDBId");

                    b.HasIndex("RegisterDBId")
                        .IsUnique()
                        .HasFilter("[RegisterDBId] IS NOT NULL");

                    b.HasIndex("AccountSnsType", "AccountSnsSub")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("WS_SB.DB.RankingDB", b =>
                {
                    b.Property<int>("RankingDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankingDBId"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserDBId")
                        .HasColumnType("int");

                    b.HasKey("RankingDBId");

                    b.HasIndex("Score");

                    b.HasIndex("UserDBId")
                        .IsUnique();

                    b.ToTable("Ranking");
                });

            modelBuilder.Entity("WS_SB.DB.RegisterDB", b =>
                {
                    b.Property<int>("RegisterDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterDBId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("RegisterDBId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("WS_SB.DB.UserDB", b =>
                {
                    b.Property<int>("UserDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDBId"));

                    b.Property<int>("AccountDBId")
                        .HasColumnType("int");

                    b.Property<int>("CostumeSetting")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("UserDBId");

                    b.HasIndex("AccountDBId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.HasOne("WS_SB.DB.RegisterDB", "Register")
                        .WithOne("Account")
                        .HasForeignKey("WS_SB.DB.AccountDB", "RegisterDBId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Register");
                });

            modelBuilder.Entity("WS_SB.DB.RankingDB", b =>
                {
                    b.HasOne("WS_SB.DB.UserDB", "User")
                        .WithOne("Ranking")
                        .HasForeignKey("WS_SB.DB.RankingDB", "UserDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WS_SB.DB.UserDB", b =>
                {
                    b.HasOne("WS_SB.DB.AccountDB", null)
                        .WithMany("Users")
                        .HasForeignKey("AccountDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS_SB.DB.AccountDB", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WS_SB.DB.RegisterDB", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("WS_SB.DB.UserDB", b =>
                {
                    b.Navigation("Ranking")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
